import { fetchJson } from "@/lib/ingest/http";
import { loadAts, parseIsoDate, type AtsCompany, type AtsJob } from "@/lib/ingest/sources/ats";
import type { Source } from "@/lib/ingest/types";

const SOURCE_NAME = "ashby";

// Display name -> Ashby job-board org slug.
const BOARDS: AtsCompany[] = [
  { company: "OpenAI", token: "openai" },
  { company: "Notion", token: "notion" },
  { company: "Ramp", token: "ramp" },
  { company: "Linear", token: "linear" },
  { company: "Perplexity", token: "perplexity" },
  { company: "Replit", token: "replit" },
  { company: "Modal", token: "modal" },
  // Verified additions:
  { company: "Cohere", token: "cohere" },
  { company: "Cursor", token: "cursor" },
  { company: "Sierra", token: "sierra" },
  { company: "ElevenLabs", token: "elevenlabs" },
  { company: "Cognition", token: "cognition" },
  { company: "Crusoe", token: "crusoe" },
  { company: "Decagon", token: "decagon" },
  { company: "Writer", token: "writer" },
  { company: "Suno", token: "suno" },
  { company: "Baseten", token: "baseten" },
  { company: "Deepgram", token: "deepgram" },
  { company: "Fireworks AI", token: "fireworks" },
  { company: "Supabase", token: "supabase" },
  { company: "PostHog", token: "posthog" },
  { company: "Watershed", token: "watershed" },
  { company: "Gamma", token: "gamma" },
  { company: "Mercor", token: "mercor" },
  { company: "Sardine", token: "sardine" },
  { company: "Character.AI", token: "character" },
  { company: "Render", token: "render" },
  { company: "Railway", token: "railway" },
  { company: "Browserbase", token: "browserbase" },
  { company: "Zed", token: "zed" },
  // More verified additions:
  { company: "Harvey", token: "harvey" },
  { company: "Vanta", token: "vanta" },
  { company: "Synthesia", token: "synthesia" },
  { company: "Lovable", token: "lovable" },
  { company: "Drata", token: "drata" },
  { company: "Granola", token: "granola" },
  { company: "Pika", token: "pika" },
  // More verified additions:
  { company: "Runway", token: "runway" },
  { company: "Lambda", token: "lambda" },
  { company: "Cartesia", token: "cartesia" },
  { company: "Physical Intelligence", token: "physicalintelligence" },
  { company: "Sesame", token: "sesame" },
  { company: "Poolside", token: "poolside" },
  { company: "OpenSea", token: "opensea" },
  { company: "Attio", token: "attio" },
  { company: "Standard Bots", token: "standardbots" },
  { company: "Warp", token: "warp" },
  { company: "Distyl", token: "distyl" },
  { company: "Pinecone", token: "pinecone" },
  { company: "Weaviate", token: "weaviate" },
  { company: "Abridge", token: "abridge" },
  { company: "OpenEvidence", token: "openevidence" },
  { company: "Reka AI", token: "reka" },
  { company: "Headway", token: "headway" },
  { company: "Dust", token: "dust" },
  { company: "Hyperbolic", token: "hyperbolic" },
  { company: "Mintlify", token: "mintlify" },
  { company: "Resend", token: "resend" },
  { company: "Etched", token: "etched" },
  { company: "WorkOS", token: "workos" },
  { company: "Stytch", token: "stytch" },
  { company: "Knock", token: "knock" },
  { company: "Cerebras", token: "cerebras" },
  { company: "Saronic", token: "saronic" },
  { company: "Vitalize", token: "vitalize" },
  { company: "Commure", token: "commure" },
  { company: "Nabla", token: "nabla" },
  { company: "LangChain", token: "langchain" },
  { company: "LlamaIndex", token: "llamaindex" },
  { company: "MotherDuck", token: "motherduck" },
  { company: "Vapi", token: "vapi" },
  { company: "Doppler", token: "doppler" },
  { company: "Neon", token: "neon" },
  { company: "Sanity", token: "sanity" },
  { company: "Braintrust", token: "braintrust" },
  { company: "Langfuse", token: "langfuse" },
  { company: "Socket", token: "socket" },
  { company: "Phantom", token: "phantom" },
  { company: "Ledger", token: "ledger" },
  { company: "WHOOP", token: "whoop" },
  { company: "Polymarket", token: "polymarket" },
  { company: "Kalshi", token: "kalshi" },
  { company: "Speak", token: "speak" },
  { company: "Rho", token: "rho" },
  { company: "Persona", token: "persona" },
  { company: "Superpower", token: "superpower" },
  { company: "Alchemy", token: "alchemy" },
  { company: "Helius", token: "helius" },
  // From speedyapply/2027-SWE-College-Jobs (probed live 2026-07-11):
  { company: "Auctor", token: "auctor" },
  { company: "Base Power", token: "base-power" },
  { company: "Beacon Software", token: "beaconsoftware" },
  { company: "Binance.US", token: "binance.us" },
  { company: "Blackstar Computers", token: "blackstar" },
  { company: "CTGT", token: "ctgt" },
  { company: "Centerfield", token: "centerfield" },
  { company: "Circleback", token: "circleback" },
  { company: "Ellipsis Labs", token: "ellipsislabs" },
  { company: "Heron Power", token: "heron-power" },
  { company: "MyJunior AI", token: "junior" },
  { company: "Phia", token: "phia" },
  { company: "Pylon", token: "pylon-labs" },
  { company: "Rivian", token: "rivianvw.tech" },
  { company: "Skydio", token: "skydio" },
  { company: "Tessera Labs", token: "tessera-labs" },
  { company: "kos.ai", token: "kos.ai" },
  // Probed live 2026-07-11 (candidate sweep):
  { company: "Airbyte", token: "airbyte" },
  { company: "Benchling", token: "benchling" },
  { company: "Boom Supersonic", token: "boom" },
  { company: "Confluent", token: "confluent" },
  { company: "Miro", token: "miro" },
  { company: "Plaid", token: "plaid" },
  { company: "Snowflake", token: "snowflake" },
  { company: "Voleon", token: "voleon" },
  { company: "1X", token: "1x" },
  { company: "Ambience Healthcare", token: "ambiencehealthcare" },
  { company: "Astronomer", token: "astronomer" },
  { company: "Chai Discovery", token: "chaidiscovery" },
  { company: "Collaborative Robotics", token: "cobot" },
  { company: "Column", token: "column" },
  { company: "Handshake", token: "handshake" },
  { company: "Ideogram", token: "ideogram" },
  { company: "Middesk", token: "middesk" },
  { company: "Modern Treasury", token: "moderntreasury" },
  { company: "Patreon", token: "patreon" },
  { company: "Prefect", token: "prefect" },
  { company: "Sentry", token: "sentry" },
  { company: "Substack", token: "substack" },
  // Probed live 2026-07-14 (candidate sweep):
  { company: "Airwallex", token: "airwallex" },
  { company: "Anyscale", token: "anyscale" },
  { company: "ClickUp", token: "clickup" },
  { company: "Extropic", token: "extropic" },
  { company: "Form Energy", token: "formenergy" },
  { company: "Helion Energy", token: "helion" },
  { company: "Normal Computing", token: "normalcomputing" },
  { company: "Span", token: "span" },
  { company: "Twelve", token: "twelve" },
  { company: "Uniswap Labs", token: "uniswap" },
  { company: "Zapier", token: "zapier" },
  // Probed live 2026-07-14 (candidate sweep, batch 2):
  { company: "Artisan", token: "artisan" },
  { company: "Bland", token: "bland" },
  { company: "Footprint", token: "footprint" },
  { company: "Lorikeet", token: "lorikeet" },
  { company: "Material Security", token: "materialsecurity" },
  { company: "Omni", token: "omni" },
  { company: "Parafin", token: "parafin" },
  { company: "Semgrep", token: "semgrep" },
  { company: "Serve Robotics", token: "serverobotics" },
  { company: "Svix", token: "svix" },
  { company: "Tavus", token: "tavus" },
  { company: "Trigger.dev", token: "triggerdev" },
  { company: "Unify", token: "unify" },
  // AI labs (probed 2026-07-21):
  { company: "Hedra", token: "hedra" },
  { company: "Krea", token: "krea" },
  { company: "Reflection AI", token: "reflectionai" },
  // Dev tools (probed 2026-07-21):
  { company: "Docker", token: "docker" },
  { company: "1Password", token: "1password" },
  // Security (probed 2026-07-21):
  { company: "Cyberhaven", token: "cyberhaven" },
  // Consumer (probed 2026-07-21):
  { company: "Strava", token: "strava" },
  // Bio / health (probed 2026-07-21):
  { company: "Insitro", token: "insitro" },
  // aggregator-mined direct boards, batch 1 (2026-07-22)
  { company: "8VC", token: "8vc" },
  { company: "Adaption Labs", token: "adaption" },
  { company: "Adaptive Security", token: "adaptivesecurity" },
  { company: "AeroVect", token: "aerovect" },
  { company: "AfterQuery", token: "afterquery" },
  { company: "Agentis Capital", token: "agentis-capital-advisors" },
  { company: "Airspace Intelligence", token: "airspace-intelligence.com" },
  { company: "Anterior", token: "anterior" },
  { company: "Apex", token: "apex-technology-inc" },
  { company: "Applied Intuition", token: "applied" },
  { company: "Aptura", token: "aptura" },
  { company: "Architect Labs", token: "architect" },
  { company: "Astera", token: "astera" },
  { company: "Basis Research Institute", token: "basis-research" },
  { company: "Bild AI", token: "bild-ai" },
  { company: "Blackbird Labs", token: "blackbird-labs-inc" },
  { company: "Blockhouse", token: "blockhouse" },
  { company: "Bloxd", token: "bloxd" },
  { company: "Brain Co.", token: "brainco" },
  { company: "Bree", token: "bree" },
  { company: "Charge Robotics", token: "charge-robotics" },
  { company: "Clera", token: "clera" },
  { company: "Clipboard Health", token: "clipboard" },
  { company: "Compa", token: "compa" },
  { company: "Composio", token: "composio" },
  { company: "Constellation Space", token: "constellationspace" },
  { company: "Context", token: "context" },
  { company: "Coverdash", token: "coverdash" },
  { company: "Creatify Lab", token: "creatify" },
  { company: "Crosby", token: "crosby" },
  { company: "CuspAI", token: "cuspai" },
  { company: "AI Intern to the CEO", token: "cyvl" },
  { company: "d-Matrix", token: "d-matrix" },
  { company: "Dandy", token: "dandy" },
  { company: "Delinea", token: "delinea" },
  { company: "Deliveroo", token: "deliveroo" },
  { company: "Dexmate", token: "dexmate" },
  { company: "Ditto", token: "ditto" },
  { company: "Ditto AI", token: "dittoai" },
  { company: "Droyd Robotics", token: "droyd" },
  { company: "Dryft", token: "dryft" },
  { company: "Egra", token: "egra" },
  { company: "Eigen Labs", token: "eigen-labs" },
  { company: "Eight Sleep", token: "eightsleep" },
  { company: "Eloquent AI", token: "eloquentai" },
  { company: "Creatify", token: "embedding-vc" },
  { company: "Equip Health", token: "equip" },
  { company: "Eragon", token: "eragon" },
  { company: "Espa AI", token: "espa" },
  { company: "ether.fi", token: "ether.fi" },
  { company: "ETHGlobal", token: "ethglobal" },
  { company: "Exa Labs", token: "exa" },
  { company: "Eyebot", token: "eyebot" },
  { company: "Atomic Semi", token: "fab2" }, // atomicsemi board is gone; fab2 is theirs
  { company: "Faculty AI", token: "faculty" },
  { company: "Faculte", token: "faculty-fellowship" },
  { company: "Farsight", token: "farsight" },
  { company: "Firetiger", token: "firetiger" },
  { company: "Flagright", token: "flagright.com" },
  { company: "Flock Safety", token: "flock" },
  { company: "Fluency", token: "fluency" },
  { company: "Frontier Health", token: "frontier-health" },
  { company: "Fundwell", token: "fundwell" },
  { company: "G2", token: "g2" },
  { company: "Gamechanger", token: "gamechanger" },
  { company: "Gecko Robotics", token: "gecko-robotics" },
  { company: "Gen Digital", token: "gen-digital" },
  { company: "GenMD", token: "genmd" },
  { company: "Georgian Partners Growth", token: "georgian" },
  { company: "Giga AI", token: "gigaml" },
  { company: "Glimpse Engineering", token: "glimp-se" },
  { company: "GoLinks", token: "golinks" },
  { company: "Gorgias", token: "gorgias" },
  { company: "Great Question", token: "greatquestion" },
  { company: "Gritt Robotics Inc", token: "gritt" },
  { company: "Gumloop", token: "gumloop" },
  { company: "H3X Technologies", token: "h3x-technologies" },
  { company: "Hadrian", token: "hadrian-automation" },
  { company: "Hawk-Eye Innovations", token: "hawkeyeinnovations" },
  { company: "Hayden AI", token: "haydenai" },
  { company: "HCompany", token: "hcompany" },
  { company: "Heron Data", token: "herondata" },
  { company: "Higharc", token: "higharc" },
  { company: "Hiverge", token: "hiverge" },
  { company: "Homebase", token: "homebase" },
  { company: "Hubs.is", token: "hubs.is" },
  { company: "Human Computer Lab", token: "human-computer-lab" },
  { company: "Illumio", token: "illumio" },
  { company: "Internship", token: "interplay" },
  { company: "Ironclad", token: "ironcladhq" },
  { company: "Juniper Square", token: "junipersquare" },
  { company: "k-ID", token: "k-id" },
  { company: "Keyrock", token: "keyrock" },
  { company: "Kinetic Systems", token: "kineticsystems" },
  { company: "Kira", token: "kira" },
  { company: "Kirin", token: "kirin" },
  { company: "Kognitos", token: "kognitos" },
  { company: "Kong", token: "kong" },
  { company: "Latitude.io", token: "latitude" },
  { company: "Leland", token: "leland" },
  { company: "LINQ", token: "linqapp" },
  { company: "Lunon", token: "lunon" },
  { company: "Lydian", token: "lydian" },
  { company: "m13", token: "m13" },
  // aggregator-mined direct boards, batch 2 (2026-07-22)
  { company: "Mach Industries", token: "mach" },
  { company: "Mach9", token: "mach9" },
  { company: "Mariana Minerals", token: "marianaminerals" },
  { company: "Matterworks", token: "matterworks" },
  { company: "Maxima", token: "maxima" },
  { company: "Medra", token: "medraai" },
  { company: "Melotech", token: "melotech" },
  { company: "Meshy", token: "meshy" },
  { company: "Mistral AI", token: "mistral.ai" },
  { company: "Monarch Money", token: "monarchmoney" },
  { company: "Monogram", token: "monogram" },
  { company: "MUBI", token: "mubi" },
  { company: "Nash", token: "nash" },
  { company: "NationGraph", token: "nationgraph" },
  { company: "NeoCognition", token: "neocognition" },
  { company: "Cybernetic Labs", token: "netic" },
  { company: "New Lantern", token: "newlantern" },
  { company: "Niural", token: "niural" },
  { company: "NOX METALS", token: "nox-metals" },
  { company: "Nuclear Promise X", token: "npx" },
  { company: "Obvious", token: "obvious" },
  { company: "Odin Dynamics, Inc", token: "odin-dynamics" },
  { company: "Odyssey", token: "odysseyml" },
  { company: "Oligo Space", token: "oligo" },
  { company: "Ontic", token: "ontic" },
  { company: "OpusClip", token: "opusclip" },
  { company: "Orbital Industries", token: "orbitalindustries" },
  { company: "Osmo", token: "osmo" },
  { company: "Outmarket AI", token: "outmarket" },
  { company: "Outpost Technologies", token: "outpostnow" },
  { company: "Output Biosciences", token: "output" },
  { company: "Overview Energy", token: "overviewenergy" },
  { company: "Parallel Web Systems", token: "parallel" },
  { company: "Parspec", token: "parspec" },
  { company: "Pebl", token: "pebl" },
  { company: "Perchwell", token: "perchwell" },
  { company: "Periodic Labs", token: "periodic-labs" },
  { company: "Persona AI", token: "persona.ai" },
  { company: "Phil", token: "phil" },
  { company: "Phlair", token: "phlair" },
  { company: "Phonely", token: "phonely" },
  { company: "Phonic", token: "phonic" },
  { company: "Polymath", token: "polymath" },
  { company: "Poshmark", token: "poshmark" },
  { company: "Prime Intellect", token: "primeintellect" },
  { company: "Prior Labs", token: "prior-labs" },
  { company: "Proxima", token: "proxima" },
  { company: "Quadrillion", token: "quadrillion-labs" },
  { company: "Reality Defender", token: "realitydefender" },
  { company: "Reflect Orbital", token: "reflect-orbital" },
  { company: "Relay Financial", token: "relayfi" },
  { company: "Remarcable", token: "remarcable-inc" },
  { company: "Revise Robotics", token: "reviserobotics" },
  { company: "ALSO", token: "ridealso" },
  { company: "Rocket Science Group", token: "rocketsciencegg" },
  { company: "Root Access", token: "root-access" },
  { company: "Rundoo", token: "rundoo" },
  { company: "SandboxAQ", token: "sandboxaq" },
  { company: "Sentra", token: "sentra" },
  { company: "Sereact", token: "sereact" },
  { company: "Serval", token: "serval" },
  { company: "Sieve", token: "sieve" },
  { company: "Simular", token: "simular" },
  { company: "Socure", token: "socure" },
  { company: "Solink", token: "solink" },
  { company: "Spacial AI", token: "spacial" },
  { company: "Super", token: "super.com" },
  { company: "Taara", token: "taaraconnect" },
  { company: "Talos", token: "talos-trading" },
  { company: "Tempo", token: "tempo-io" },
  { company: "TENEX.AI", token: "tenex" },
  { company: "TensorWave", token: "tensorwave" },
  { company: "Terranova", token: "terranova" },
  { company: "The Exploration Company", token: "the-exploration-company" },
  { company: "Tilde Research", token: "tilderesearch" },
  { company: "tldraw", token: "tldraw" },
  { company: "Tonal", token: "tonal" },
  { company: "Treefera", token: "treefera" },
  { company: "Triumph", token: "triumph-arcade" },
  { company: "Roam", token: "tryroam" },
  { company: "Turion Space", token: "turion-space" },
  { company: "UiPath", token: "uipath" },
  { company: "Uncountable", token: "uncountable" },
  { company: "Unlikely AI", token: "unlikelyai" },
  { company: "Unwrap", token: "unwrap" },
  { company: "Upvest", token: "upvest" },
  { company: "Vantage", token: "vantage" },
  { company: "Varick Agents", token: "varick-agents" },
  { company: "Veeda AI", token: "veeda-labs" },
  { company: "Vega Investment Technologies", token: "vega" },
  { company: "Vendelux", token: "vendelux" },
  { company: "Vital Lyfe", token: "vital-lyfe" },
  { company: "Vmax AI Corp", token: "vmax" },
  { company: "Voldex", token: "voldex" },
  { company: "Walrus", token: "walrusfi" },
  { company: "Wealth.com", token: "wealth-com" },
  { company: "Wealthsimple", token: "wealthsimple" },
  { company: "WebAI", token: "webai" },
  { company: "WindBorne Systems", token: "windborne-systems" },
  { company: "Worldly", token: "worldly" },
  { company: "Zello", token: "zello" },
  { company: "Zip", token: "zip" },
  { company: "Zuru", token: "zuru" },
  // Moved off Greenhouse (confirmed 2026-08-04):
  { company: "Thinking Machines", token: "thinkingmachines" },
  // Probed live 2026-08-04 (2027-cycle sweep). Ashby slugs are case-sensitive
  // and some orgs use a spaced display name as the slug — hence the encoding in
  // fetchCompany below.
  { company: "Kraken", token: "kraken.com" },
  { company: "Hinge Health", token: "hinge-health" },
  { company: "Clerk", token: "Clerk" },
  { company: "Redis", token: "redis" },
  { company: "InfluxData", token: "influxdata" },
  { company: "Luma AI", token: "lumaai" },
  { company: "OpenRouter", token: "openrouter" },
  { company: "Coder", token: "coder" },
  { company: "E2B", token: "e2b" },
  { company: "Rain", token: "rain" },
  { company: "Tools for Humanity", token: "Tools for Humanity" },
  { company: "General Intuition", token: "generalintuition-medal" },
  { company: "NTT DATA AIVista", token: "ntt-data-aivista" },
  { company: "Verne Robotics", token: "Verne Robotics" },
  { company: "Remedy Scientific", token: "Remedy Scientific" },
  { company: "Heliux", token: "heliux" },
  { company: "Kastle AI", token: "kastle" },
  { company: "Melius", token: "melius" },
  { company: "Alljoined", token: "alljoined" },
  { company: "Yotta Labs", token: "yotta" },
  { company: "Zettabyte", token: "zettabyte-space" },
  { company: "Forus", token: "forus" },
  { company: "Colonist", token: "colonist" },
  { company: "RapDev", token: "rapdev" },
  { company: "Sweatpals", token: "sweatpals" },
  // Quant / trading:
  { company: "Cubist Systematic Strategies", token: "cubist" },
  { company: "Anthelion Capital", token: "anthelioncap" },

  // Mined 2026-08-05 from the aggregator feeds' apply-URLs (they embed the ATS
  // token verbatim), then each of these 246 boards probed once and kept only on
  // a 200 with at least one live posting. Screened three ways before landing:
  // one board per employer, no company already covered by another source (a
  // second display name for one employer splits it in two — company feeds
  // listingId), and the display name taken from the ATS's own board name where
  // it reports one, else from the feed.
  { company: "9fin", token: "9fin" },
  { company: "Abby Care", token: "abby-care" },
  { company: "Abound", token: "Abound" },
  { company: "Acorns", token: "Acorns" },
  { company: "Aditude", token: "aditude" },
  { company: "algo1", token: "algo1" },
  { company: "Allica Bank", token: "allica-bank" },
  { company: "AlphaLife Sciences", token: "alphalifesci" },
  { company: "Alta Ares", token: "alta-ares" },
  { company: "Amigo AI", token: "amigo" },
  { company: "Amplify", token: "amplify" },
  { company: "Ando", token: "ando" },
  { company: "Angle Health", token: "anglehealth" },
  { company: "Anima", token: "anima" },
  { company: "Antares Nuclear", token: "Antares" },
  { company: "Anything", token: "anything" },
  { company: "Apiphany", token: "apiphany" },
  { company: "Apron", token: "apron" },
  { company: "Archy", token: "archy" },
  { company: "ARQ", token: "arq" },
  { company: "Ashby", token: "ashby" },
  { company: "Assembled", token: "assembledhq" },
  { company: "Astro Mechanica", token: "astro-mechanica" },
  { company: "Atomic Invest (AtomicVest)", token: "atomic-invest" },
  { company: "Atominvest", token: "atominvest" },
  { company: "Augmodo", token: "augmodo" },
  { company: "Aurelian", token: "aurelian" },
  { company: "Aurelius Systems", token: "aureliussystems" },
  { company: "Authorium", token: "Authorium" },
  { company: "Avoca AI", token: "avoca" },
  { company: "Backbone Systems", token: "backbone" },
  { company: "Baton Corporation", token: "batoncorporation" },
  { company: "Beacon AI", token: "beaconai" },
  { company: "Blissway", token: "blissway" },
  { company: "Blitzy", token: "blitzy" },
  { company: "Brainbase Labs", token: "brainbaselabs" },
  { company: "Bridger", token: "bridger" },
  { company: "BRINC Drones", token: "brinc" },
  { company: "Broccoli AI", token: "broccoli" },
  { company: "candidate fyi", token: "candidate.fyi" },
  { company: "Cantina", token: "cantina" },
  { company: "Capy", token: "capy" },
  { company: "Carwow", token: "Carwow" },
  { company: "Castle", token: "castle" },
  { company: "Chamber Cardio", token: "chambercardio" },
  { company: "Checkout.com", token: "checkout.com" },
  { company: "Citizen Health", token: "Citizen Health" },
  { company: "CivilGrid", token: "civilgrid" },
  { company: "ClaimSorted", token: "claimsorted" },
  { company: "Clarium", token: "clarium" },
  { company: "Clasp", token: "clasp-group" },
  { company: "Clay", token: "claylabs" },
  { company: "Close", token: "Close" },
  { company: "Cogent Security", token: "cogent-security" },
  { company: "Cohort AI Inc.", token: "cohort" },
  { company: "Collective", token: "collective" },
  { company: "Color", token: "color-health" },
  { company: "Concourse", token: "concourse" },
  { company: "Confido", token: "confido" },
  { company: "Corvus Robotics", token: "corvus-robotics" },
  { company: "Cylake", token: "cylake-inc" },
  { company: "DailyPay", token: "dailypay" },
  { company: "Dome Systems Inc", token: "dome-systems-inc" },
  { company: "Dyna Robotics", token: "dyna-robotics" },
  { company: "E Source Companies", token: "e-source" },
  { company: "Ekho", token: "Ekho" },
  { company: "EliseAI", token: "EliseAI" },
  { company: "Eliza", token: "eliza" },
  { company: "Ema", token: "ema" },
  { company: "Encord", token: "encord" },
  { company: "endeavorai.com", token: "endeavorai" },
  { company: "Envision Horizons LLC", token: "envision-horizons" },
  { company: "Faros AI", token: "faros-ai" },
  { company: "Feathery", token: "feathery" },
  { company: "Flashpoint", token: "flashpoint.io" },
  { company: "FluidStack", token: "fluidstack" },
  { company: "Focal", token: "focal" },
  { company: "Foxglove", token: "foxglove" },
  { company: "Frec Markets", token: "frec" },
  { company: "FS Studio", token: "fs-studio" },
  { company: "Fundamental Research Labs", token: "fundamentalresearchlabs" },
  { company: "Funding Circle", token: "fundingcircle" },
  { company: "Fuse Energy", token: "Fuse" },
  { company: "Gallatin AI", token: "gallatin" },
  { company: "Gearset", token: "gearset" },
  { company: "Generalist", token: "generalist" },
  { company: "Gimlet Labs", token: "gimlet" },
  { company: "Glia", token: "glia" },
  { company: "Glide", token: "glide" },
  { company: "GoodShip", token: "goodship" },
  { company: "GovSignals", token: "GovSignals" },
  { company: "GovWell", token: "govwell" },
  { company: "Gradient Robotics", token: "gradientrobotics" },
  { company: "GreenLite", token: "greenlitecareers" },
  { company: "GridCARE", token: "gridcare" },
  { company: "Harper Group", token: "harperinsure" },
  { company: "HavocAI", token: "havocai" },
  { company: "Healf", token: "healf" },
  { company: "Heidi Health", token: "heidihealth.com.au" },
  { company: "Highbeam", token: "highbeam" },
  { company: "Hiive", token: "hiive" },
  { company: "Hilbert", token: "hilberts" },
  { company: "Hipp Health", token: "hipp" },
  { company: "Hippocratic AI", token: "Hippocratic AI" },
  { company: "Hire Hangar", token: "hirehangar" },
  { company: "HUMAN", token: "HUMAN" },
  { company: "hyperexponential", token: "hyperexponential" },
  { company: "Iambic Therapeutics", token: "iambic-therapeutics" },
  { company: "ibotta", token: "ibotta" },
  { company: "Icon", token: "icon" },
  { company: "Imprint", token: "imprint" },
  { company: "Inclined Technologies", token: "Inclined" },
  { company: "iwoca", token: "iwoca.co.uk" },
  { company: "Jerry", token: "jerry.ai" },
  { company: "Jigsaw", token: "jigsaw" },
  { company: "Julius AI", token: "julius" },
  { company: "KAYAK", token: "KAYAK" },
  { company: "Klarity", token: "klarity-ai" },
  { company: "Klue", token: "klue" },
  { company: "Kustomer", token: "kustomer" },
  { company: "LawDepot", token: "lawdepot" },
  { company: "Layer Financial Technologies", token: "layerfi" },
  { company: "Leavitt Group", token: "leavitt" },
  { company: "Lendable", token: "lendable" },
  { company: "LG Ad Solutions", token: "lgads" },
  { company: "Lightfield", token: "Lightfield" },
  { company: "Lightspark", token: "lightspark" },
  { company: "Limble CMMS", token: "limble" },
  { company: "Liquid", token: "liquid" },
  { company: "LiveFlow", token: "liveflow" },
  { company: "Logiqal", token: "logiqal" },
  { company: "Logos Space", token: "logos-space" },
  { company: "loveholidays", token: "loveholidays" },
  { company: "Lynk", token: "Lynk" },
  { company: "Magical", token: "magical" },
  { company: "Maigrate", token: "maigrate" },
  { company: "Makai Labs", token: "makai-labs" },
  { company: "Mandolin", token: "mandolin" },
  { company: "Maple AI", token: "maple" },
  { company: "Matic", token: "MaticRobots" },
  { company: "Maya HTT", token: "maya-htt" },
  { company: "Mechanize", token: "mechanize" },
  { company: "Meridian Link", token: "meridianlink" },
  { company: "Meticulous", token: "meticulous" },
  { company: "Miovision", token: "miovision" },
  { company: "Mirage", token: "mirage" },
  { company: "Moab", token: "moab" },
  { company: "Moss", token: "moss" },
  { company: "Motorway", token: "motorway" },
  { company: "Mudflap", token: "mudflap" },
  { company: "N1", token: "n1" },
  { company: "Nascent", token: "nascent" },
  { company: "Nectar Social", token: "nectar-social" },
  { company: "Neon Health", token: "neon-health" },
  { company: "Nexxen", token: "nexxen" },
  { company: "Northslope Technologies", token: "northslope-technologies" },
  { company: "Northwood Space", token: "NorthwoodSpace" },
  { company: "NORY", token: "nory-co" },
  { company: "Numeral", token: "numeral" },
  { company: "NumerixS Quant", token: "numerixs-quant" },
  { company: "Observable Space", token: "observable-space" },
  { company: "One Brief", token: "onebrief" },
  { company: "OpenGov", token: "opengov" },
  { company: "Orb", token: "orb" },
  { company: "Orchard", token: "orchard" },
  { company: "Packz", token: "packz" },
  { company: "PAR Tech", token: "PAR Technology" },
  { company: "Paradigm", token: "paradigm" },
  { company: "Pariveda Solutions", token: "pariveda" },
  { company: "Pearl Health", token: "pearlhealth" },
  { company: "People Culture Talent", token: "people-culture-talent" },
  { company: "PermitFlow", token: "permitflow" },
  { company: "Picogrid", token: "picogrid" },
  { company: "Pogo Technologies", token: "joinpogo" },
  { company: "PointOne", token: "PointOne" },
  { company: "Preference Model", token: "Preference-Model" },
  { company: "Prelim", token: "prelim" },
  { company: "Probook", token: "probook" },
  { company: "Profound", token: "Profound" },
  { company: "Quantcast", token: "quantcast" },
  { company: "Quantexa", token: "quantexa" },
  { company: "Quantum", token: "quantum" },
  { company: "Quora", token: "quora" },
  { company: "Realm", token: "realmalliance" },
  { company: "Relation Therapeutics", token: "relationrx" },
  { company: "Relay Technologies", token: "relay" },
  { company: "Retell AI", token: "retell-ai" },
  { company: "Revel", token: "revel" },
  { company: "RevenueCat", token: "revenuecat" },
  { company: "Rhoda AI", token: "rhoda-ai" },
  { company: "Rivet Industries", token: "rivet" },
  { company: "Rollout", token: "rollout" },
  { company: "Runpod", token: "runpod" },
  { company: "RunSybil", token: "runsybil-jobs" },
  { company: "Sauna", token: "sauna.ai" },
  { company: "Sciforium", token: "Sciforium" },
  { company: "SentiLink", token: "sentilink" },
  { company: "SewerAI", token: "sewer-ai" },
  { company: "Shepherd", token: "shepherd" },
  { company: "Shiftsmart", token: "shiftsmart" },
  { company: "Silna Health", token: "silnahealth.com" },
  { company: "Simile", token: "simile" },
  { company: "Simple AI", token: "simple-ai" },
  { company: "Slingshot AI", token: "slingshotai" },
  { company: "Smarkets", token: "smarkets" },
  { company: "Solace Health", token: "solace" },
  { company: "SPAICE Technology", token: "spaice-tech" },
  { company: "SpAItial", token: "spaitial" },
  { company: "Specter", token: "specter" },
  { company: "Squint", token: "squint.ai" },
  { company: "Standard Fleet", token: "standardfleet" },
  { company: "Starbridge", token: "starbridge" },
  { company: "Starpath Robotics", token: "starpath.space" },
  { company: "Strada", token: "stradahq" },
  { company: "Strala Group", token: "strala-ai" },
  { company: "Sunday Robotics", token: "sunday" },
  { company: "Sylvera", token: "sylvera" },
  { company: "Tacit", token: "tacit" },
  { company: "Tandem PV", token: "tandempv" },
  { company: "Tavily", token: "tavily" },
  { company: "Teamworks", token: "teamworks" },
  { company: "Teleskope", token: "teleskope" },
  { company: "TELUS Digital", token: "telus-digital" },
  { company: "Teza Technologies", token: "teza-technologies" },
  { company: "The Job Sauce", token: "The Job Sauce" },
  { company: "Titan", token: "titan-msp" },
  { company: "Tolan", token: "tolan" },
  { company: "Traba", token: "traba" },
  { company: "Tracebit", token: "tracebit" },
  { company: "Trading212", token: "trading212" },
  { company: "Trainline", token: "trainline" },
  { company: "Treeswift", token: "treeswift" },
  { company: "TRM Labs", token: "trm-labs" },
  { company: "Turn/River Capital", token: "turn-river" },
  { company: "Two Dots", token: "two-dots" },
  { company: "United Talent Agency", token: "united-talent-agency" },
  { company: "Usul", token: "usul" },
  { company: "Valinor", token: "valinor" },
  { company: "Valon", token: "Valon" },
  { company: "Valstad", token: "valstad" },
  { company: "Verse Medical", token: "versemedical" },
  { company: "Voxel", token: "voxel" },
  { company: "Vytalize Health", token: "Vytalize Health" },
  { company: "Watney", token: "watney" },
  { company: "ZeroMark", token: "zeromark" },
  { company: "Zilch", token: "zilch" },
  // Mined 2026-08-10 from the new-grad aggregator feeds' apply-URLs, then
  // each board probed against the live API and kept only on a 200 with at
  // least one open posting. Same screen as the 08-05 batch: one board per
  // employer, and nothing already covered here or by another source.
  { company: "Teya", token: "teya" },
];

interface AshbyJob {
  title?: unknown;
  // Ashby gives a structured address; addressCountry is a full name
  // ("United States"), which normalizeCountryCode maps to an ISO code.
  address?: { postalAddress?: { addressCountry?: unknown } | null } | null;
  jobUrl?: unknown;
  applyUrl?: unknown;
  publishedAt?: unknown;
  location?: unknown;
  isListed?: unknown;
}

async function fetchCompany(c: AtsCompany): Promise<AtsJob[]> {
  // Some orgs' slugs contain spaces (e.g. "Tools for Humanity"), so encode.
  // Safe for the existing dotted slugs — encodeURIComponent leaves . - _ alone.
  const raw = await fetchJson(
    `https://api.ashbyhq.com/posting-api/job-board/${encodeURIComponent(c.token)}`,
  );
  const jobs = (raw as { jobs?: AshbyJob[] })?.jobs ?? [];
  return jobs
    .filter((j) => j.isListed !== false)
    .map((j) => ({
      title: typeof j.title === "string" ? j.title.trim() : "",
      locations: typeof j.location === "string" ? [j.location.trim()] : [],
      country: j.address?.postalAddress?.addressCountry,
      url:
        (typeof j.jobUrl === "string" && j.jobUrl) ||
        (typeof j.applyUrl === "string" && j.applyUrl) ||
        "",
      datePosted: parseIsoDate(j.publishedAt),
    }));
}

export const ashbySource: Source = {
  name: SOURCE_NAME,
  load: () => loadAts({ sourceName: SOURCE_NAME, companies: BOARDS, fetchCompany }),
};
