import { fetchJson } from "@/lib/ingest/http";
import { loadAts, parseIsoDate, type AtsCompany, type AtsJob } from "@/lib/ingest/sources/ats";
import type { Source } from "@/lib/ingest/types";

const SOURCE_NAME = "ashby";

// Display name -> Ashby job-board org slug.
const BOARDS: AtsCompany[] = [
  { company: "OpenAI", token: "openai" },
  { company: "Notion", token: "notion" },
  { company: "Ramp", token: "ramp" },
  { company: "Linear", token: "linear" },
  { company: "Perplexity", token: "perplexity" },
  { company: "Replit", token: "replit" },
  { company: "Modal", token: "modal" },
  // Verified additions:
  { company: "Cohere", token: "cohere" },
  { company: "Cursor", token: "cursor" },
  { company: "Sierra", token: "sierra" },
  { company: "ElevenLabs", token: "elevenlabs" },
  { company: "Cognition", token: "cognition" },
  { company: "Crusoe", token: "crusoe" },
  { company: "Decagon", token: "decagon" },
  { company: "Writer", token: "writer" },
  { company: "Suno", token: "suno" },
  { company: "Baseten", token: "baseten" },
  { company: "Deepgram", token: "deepgram" },
  { company: "Fireworks AI", token: "fireworksai" },
  { company: "Supabase", token: "supabase" },
  { company: "PostHog", token: "posthog" },
  { company: "Watershed", token: "watershed" },
  { company: "Gamma", token: "gamma" },
  { company: "Mercor", token: "mercor" },
  { company: "Sardine", token: "sardine" },
  { company: "Character.AI", token: "character" },
  { company: "Render", token: "render" },
  { company: "Railway", token: "railway" },
  { company: "Browserbase", token: "browserbase" },
  { company: "Zed", token: "zed" },
  // More verified additions:
  { company: "Harvey", token: "harvey" },
  { company: "Vanta", token: "vanta" },
  { company: "Synthesia", token: "synthesia" },
  { company: "Lovable", token: "lovable" },
  { company: "Drata", token: "drata" },
  { company: "Granola", token: "granola" },
  { company: "Pika", token: "pika" },
  // More verified additions:
  { company: "Runway", token: "runway" },
  { company: "Lambda", token: "lambda" },
  { company: "Cartesia", token: "cartesia" },
  { company: "Physical Intelligence", token: "physicalintelligence" },
  { company: "Sesame", token: "sesame" },
  { company: "Poolside", token: "poolside" },
  { company: "OpenSea", token: "opensea" },
  { company: "Attio", token: "attio" },
  { company: "Standard Bots", token: "standardbots" },
  { company: "Warp", token: "warp" },
  { company: "Distyl", token: "distyl" },
  { company: "Pinecone", token: "pinecone" },
  { company: "Weaviate", token: "weaviate" },
  { company: "Abridge", token: "abridge" },
  { company: "OpenEvidence", token: "openevidence" },
  { company: "Reka AI", token: "reka" },
  { company: "Headway", token: "headway" },
  { company: "Dust", token: "dust" },
  { company: "Hyperbolic", token: "hyperbolic" },
  { company: "Mintlify", token: "mintlify" },
  { company: "Resend", token: "resend" },
  { company: "Etched", token: "etched" },
  { company: "WorkOS", token: "workos" },
  { company: "Stytch", token: "stytch" },
  { company: "Knock", token: "knock" },
  { company: "Cerebras", token: "cerebras" },
  { company: "Saronic", token: "saronic" },
  { company: "Vitalize", token: "vitalize" },
  { company: "Commure", token: "commure" },
  { company: "Nabla", token: "nabla" },
  { company: "LangChain", token: "langchain" },
  { company: "LlamaIndex", token: "llamaindex" },
  { company: "MotherDuck", token: "motherduck" },
  { company: "Vapi", token: "vapi" },
  { company: "Doppler", token: "doppler" },
  { company: "Neon", token: "neon" },
  { company: "Sanity", token: "sanity" },
  { company: "Braintrust", token: "braintrust" },
  { company: "Langfuse", token: "langfuse" },
  { company: "Socket", token: "socket" },
  { company: "Phantom", token: "phantom" },
  { company: "Ledger", token: "ledger" },
  { company: "WHOOP", token: "whoop" },
  { company: "Polymarket", token: "polymarket" },
  { company: "Kalshi", token: "kalshi" },
  { company: "Speak", token: "speak" },
  { company: "Rho", token: "rho" },
  { company: "Persona", token: "persona" },
  { company: "Superpower", token: "superpower" },
  { company: "Alchemy", token: "alchemy" },
  { company: "Helius", token: "helius" },
  // From speedyapply/2027-SWE-College-Jobs (probed live 2026-07-11):
  { company: "Atomic Semi", token: "atomicsemi" },
  { company: "Auctor", token: "auctor" },
  { company: "Base Power", token: "base-power" },
  { company: "Beacon Software", token: "beaconsoftware" },
  { company: "Binance.US", token: "binance.us" },
  { company: "Blackstar Computers", token: "blackstar" },
  { company: "CTGT", token: "ctgt" },
  { company: "Centerfield", token: "centerfield" },
  { company: "Circleback", token: "circleback" },
  { company: "Ellipsis Labs", token: "ellipsislabs" },
  { company: "Heron Power", token: "heron-power" },
  { company: "MyJunior AI", token: "junior" },
  { company: "Phia", token: "phia" },
  { company: "Pylon", token: "pylon-labs" },
  { company: "Rivian", token: "rivianvw.tech" },
  { company: "Skydio", token: "skydio" },
  { company: "Tessera Labs", token: "tessera-labs" },
  { company: "kos.ai", token: "kos.ai" },
  // Probed live 2026-07-11 (candidate sweep):
  { company: "Airbyte", token: "airbyte" },
  { company: "Benchling", token: "benchling" },
  { company: "Boom Supersonic", token: "boom" },
  { company: "Confluent", token: "confluent" },
  { company: "Miro", token: "miro" },
  { company: "Plaid", token: "plaid" },
  { company: "Snowflake", token: "snowflake" },
  { company: "Voleon", token: "voleon" },
  { company: "1X", token: "1x" },
  { company: "Ambience Healthcare", token: "ambiencehealthcare" },
  { company: "Astronomer", token: "astronomer" },
  { company: "Chai Discovery", token: "chaidiscovery" },
  { company: "Collaborative Robotics", token: "cobot" },
  { company: "Column", token: "column" },
  { company: "Handshake", token: "handshake" },
  { company: "Ideogram", token: "ideogram" },
  { company: "Middesk", token: "middesk" },
  { company: "Modern Treasury", token: "moderntreasury" },
  { company: "Patreon", token: "patreon" },
  { company: "Prefect", token: "prefect" },
  { company: "Sentry", token: "sentry" },
  { company: "Substack", token: "substack" },
  // Probed live 2026-07-14 (candidate sweep):
  { company: "Airwallex", token: "airwallex" },
  { company: "Anyscale", token: "anyscale" },
  { company: "ClickUp", token: "clickup" },
  { company: "Extropic", token: "extropic" },
  { company: "Form Energy", token: "formenergy" },
  { company: "Helion Energy", token: "helion" },
  { company: "Normal Computing", token: "normalcomputing" },
  { company: "Span", token: "span" },
  { company: "Twelve", token: "twelve" },
  { company: "Uniswap Labs", token: "uniswap" },
  { company: "Zapier", token: "zapier" },
  // Probed live 2026-07-14 (candidate sweep, batch 2):
  { company: "Artisan", token: "artisan" },
  { company: "Bland", token: "bland" },
  { company: "Footprint", token: "footprint" },
  { company: "Lorikeet", token: "lorikeet" },
  { company: "Material Security", token: "materialsecurity" },
  { company: "Omni", token: "omni" },
  { company: "Parafin", token: "parafin" },
  { company: "Semgrep", token: "semgrep" },
  { company: "Serve Robotics", token: "serverobotics" },
  { company: "Svix", token: "svix" },
  { company: "Tavus", token: "tavus" },
  { company: "Trigger.dev", token: "triggerdev" },
  { company: "Unify", token: "unify" },
  // AI labs (probed 2026-07-21):
  { company: "Hedra", token: "hedra" },
  { company: "Krea", token: "krea" },
  { company: "Reflection AI", token: "reflectionai" },
  // Dev tools (probed 2026-07-21):
  { company: "Docker", token: "docker" },
  { company: "1Password", token: "1password" },
  // Security (probed 2026-07-21):
  { company: "Cyberhaven", token: "cyberhaven" },
  // Consumer (probed 2026-07-21):
  { company: "Strava", token: "strava" },
  // Bio / health (probed 2026-07-21):
  { company: "Insitro", token: "insitro" },
  // aggregator-mined direct boards, batch 1 (2026-07-22)
  { company: "8VC", token: "8vc" },
  { company: "Adaption Labs", token: "adaption" },
  { company: "Adaptive Security", token: "adaptivesecurity" },
  { company: "AeroVect", token: "aerovect" },
  { company: "AfterQuery", token: "afterquery" },
  { company: "Agentis Capital", token: "agentis-capital-advisors" },
  { company: "Airspace Intelligence", token: "airspace-intelligence.com" },
  { company: "Anterior", token: "anterior" },
  { company: "Apex", token: "apex-technology-inc" },
  { company: "Applied Intuition", token: "applied" },
  { company: "Aptura", token: "aptura" },
  { company: "Architect Labs", token: "architect" },
  { company: "Astera", token: "astera" },
  { company: "Basis Research Institute", token: "basis-research" },
  { company: "Bild AI", token: "bild-ai" },
  { company: "Blackbird Labs", token: "blackbird-labs-inc" },
  { company: "Blockhouse", token: "blockhouse" },
  { company: "Bloxd", token: "bloxd" },
  { company: "Brain Co.", token: "brainco" },
  { company: "Bree", token: "bree" },
  { company: "Charge Robotics", token: "charge-robotics" },
  { company: "Clera", token: "clera" },
  { company: "Clipboard Health", token: "clipboard" },
  { company: "Compa", token: "compa" },
  { company: "Composio", token: "composio" },
  { company: "Constellation Space", token: "constellationspace" },
  { company: "Context", token: "context" },
  { company: "Coverdash", token: "coverdash" },
  { company: "Creatify Lab", token: "creatify" },
  { company: "Crosby", token: "crosby" },
  { company: "CuspAI", token: "cuspai" },
  { company: "AI Intern to the CEO", token: "cyvl" },
  { company: "d-Matrix", token: "d-matrix" },
  { company: "Dandy", token: "dandy" },
  { company: "Delinea", token: "delinea" },
  { company: "Deliveroo", token: "deliveroo" },
  { company: "Dexmate", token: "dexmate" },
  { company: "Ditto", token: "ditto" },
  { company: "Ditto AI", token: "dittoai" },
  { company: "Droyd Robotics", token: "droyd" },
  { company: "Dryft", token: "dryft" },
  { company: "Egra", token: "egra" },
  { company: "Eigen Labs", token: "eigen-labs" },
  { company: "Eight Sleep", token: "eightsleep" },
  { company: "Eloquent AI", token: "eloquentai" },
  { company: "Creatify", token: "embedding-vc" },
  { company: "Equip Health", token: "equip" },
  { company: "Eragon", token: "eragon" },
  { company: "Espa AI", token: "espa" },
  { company: "ether.fi", token: "ether.fi" },
  { company: "ETHGlobal", token: "ethglobal" },
  { company: "Exa Labs", token: "exa" },
  { company: "Eyebot", token: "eyebot" },
  { company: "Fab2", token: "fab2" },
  { company: "Faculty AI", token: "faculty" },
  { company: "Faculte", token: "faculty-fellowship" },
  { company: "Farsight", token: "farsight" },
  { company: "Firetiger", token: "firetiger" },
  { company: "Flagright", token: "flagright.com" },
  { company: "Flock Safety", token: "flock" },
  { company: "Fluency", token: "fluency" },
  { company: "Frontier Health", token: "frontier-health" },
  { company: "Fundwell", token: "fundwell" },
  { company: "G2", token: "g2" },
  { company: "Gamechanger", token: "gamechanger" },
  { company: "Gecko Robotics", token: "gecko-robotics" },
  { company: "Gen Digital", token: "gen-digital" },
  { company: "GenMD", token: "genmd" },
  { company: "Georgian Partners Growth", token: "georgian" },
  { company: "Giga AI", token: "gigaml" },
  { company: "Glimpse Engineering", token: "glimp-se" },
  { company: "GoLinks", token: "golinks" },
  { company: "Gorgias", token: "gorgias" },
  { company: "Great Question", token: "greatquestion" },
  { company: "Gritt Robotics Inc", token: "gritt" },
  { company: "Gumloop", token: "gumloop" },
  { company: "H3X Technologies", token: "h3x-technologies" },
  { company: "Hadrian", token: "hadrian-automation" },
  { company: "Hawk-Eye Innovations", token: "hawkeyeinnovations" },
  { company: "Hayden AI", token: "haydenai" },
  { company: "HCompany", token: "hcompany" },
  { company: "Heron Data", token: "herondata" },
  { company: "Higharc", token: "higharc" },
  { company: "Hiverge", token: "hiverge" },
  { company: "Homebase", token: "homebase" },
  { company: "Hubs.is", token: "hubs.is" },
  { company: "Human Computer Lab", token: "human-computer-lab" },
  { company: "Illumio", token: "illumio" },
  { company: "Internship", token: "interplay" },
  { company: "Ironclad", token: "ironcladhq" },
  { company: "Juniper Square", token: "junipersquare" },
  { company: "k-ID", token: "k-id" },
  { company: "Keyrock", token: "keyrock" },
  { company: "Kinetic Systems", token: "kineticsystems" },
  { company: "Kira", token: "kira" },
  { company: "Kirin", token: "kirin" },
  { company: "Kognitos", token: "kognitos" },
  { company: "Kong", token: "kong" },
  { company: "Latitude.io", token: "latitude" },
  { company: "Leland", token: "leland" },
  { company: "LINQ", token: "linqapp" },
  { company: "Lunon", token: "lunon" },
  { company: "Lydian", token: "lydian" },
  { company: "m13", token: "m13" },
];

interface AshbyJob {
  title?: unknown;
  jobUrl?: unknown;
  applyUrl?: unknown;
  publishedAt?: unknown;
  location?: unknown;
  isListed?: unknown;
}

async function fetchCompany(c: AtsCompany): Promise<AtsJob[]> {
  const raw = await fetchJson(
    `https://api.ashbyhq.com/posting-api/job-board/${c.token}`,
  );
  const jobs = (raw as { jobs?: AshbyJob[] })?.jobs ?? [];
  return jobs
    .filter((j) => j.isListed !== false)
    .map((j) => ({
      title: typeof j.title === "string" ? j.title.trim() : "",
      locations: typeof j.location === "string" ? [j.location.trim()] : [],
      url:
        (typeof j.jobUrl === "string" && j.jobUrl) ||
        (typeof j.applyUrl === "string" && j.applyUrl) ||
        "",
      datePosted: parseIsoDate(j.publishedAt),
    }));
}

export const ashbySource: Source = {
  name: SOURCE_NAME,
  load: () => loadAts({ sourceName: SOURCE_NAME, companies: BOARDS, fetchCompany }),
};
