import { fetchJson } from "@/lib/ingest/http";
import { loadAts, parseIsoDate, type AtsCompany, type AtsJob } from "@/lib/ingest/sources/ats";
import type { Source } from "@/lib/ingest/types";

const SOURCE_NAME = "greenhouse";

// Display name -> Greenhouse board token. Tokens verified against
// boards-api.greenhouse.io during development; prune any that 404.
const BOARDS: AtsCompany[] = [
  { company: "Stripe", token: "stripe" },
  { company: "Databricks", token: "databricks" },
  { company: "Airbnb", token: "airbnb" },
  { company: "Robinhood", token: "robinhood" },
  { company: "Coinbase", token: "coinbase" },
  { company: "Instacart", token: "instacart" },
  { company: "Reddit", token: "reddit" },
  { company: "Pinterest", token: "pinterest" },
  { company: "Dropbox", token: "dropbox" },
  { company: "Gusto", token: "gusto" },
  { company: "Brex", token: "brex" },
  { company: "Discord", token: "discord" },
  { company: "Cloudflare", token: "cloudflare" },
  { company: "Asana", token: "asana" },
  { company: "Samsara", token: "samsara" },
  { company: "Affirm", token: "affirm" },
  { company: "Chime", token: "chime" },
  { company: "Gemini", token: "gemini" },
  { company: "Faire", token: "faire" },
  { company: "Flexport", token: "flexport" },
  { company: "Nextdoor", token: "nextdoor" },
  { company: "SoFi", token: "sofi" },
  { company: "Lyft", token: "lyft" },
  { company: "Twilio", token: "twilio" },
  { company: "Anduril", token: "andurilindustries" },
  { company: "Verkada", token: "verkada" },
  { company: "Airtable", token: "airtable" },
  { company: "Toast", token: "toast" },
  { company: "Block", token: "block" },
  // Verified additions:
  { company: "DoorDash", token: "doordashusa" },
  { company: "Datadog", token: "datadog" },
  { company: "Roblox", token: "roblox" },
  { company: "Figma", token: "figma" },
  { company: "GitLab", token: "gitlab" },
  { company: "MongoDB", token: "mongodb" },
  { company: "Elastic", token: "elastic" },
  { company: "Squarespace", token: "squarespace" },
  { company: "Checkr", token: "checkr" },
  { company: "Webflow", token: "webflow" },
  { company: "Okta", token: "okta" },
  { company: "PagerDuty", token: "pagerduty" },
  { company: "Twitch", token: "twitch" },
  { company: "Peloton", token: "peloton" },
  { company: "Scale AI", token: "scaleai" },
  { company: "Anthropic", token: "anthropic" },
  { company: "Nuro", token: "nuro" },
  { company: "Sigma Computing", token: "sigmacomputing" },
  { company: "Grafana", token: "grafanalabs" },
  { company: "Cockroach Labs", token: "cockroachlabs" },
  { company: "ClickHouse", token: "clickhouse" },
  { company: "Temporal", token: "temporaltechnologies" },
  { company: "Fivetran", token: "fivetran" },
  { company: "Hightouch", token: "hightouch" },
  { company: "Duolingo", token: "duolingo" },
  { company: "StockX", token: "stockx" },
  // Quant / trading:
  { company: "Jane Street", token: "janestreet" },
  { company: "Jump Trading", token: "jumptrading" },
  { company: "IMC Trading", token: "imc" },
  { company: "Akuna Capital", token: "akunacapital" },
  { company: "Old Mission Capital", token: "oldmissioncapital" },
  { company: "Tower Research Capital", token: "towerresearchcapital" },
  { company: "PDT Partners", token: "pdtpartners" },
  { company: "Squarepoint Capital", token: "squarepointcapital" },
  { company: "Flow Traders", token: "flowtraders" },
  // More verified additions:
  { company: "Gong", token: "gongio" },
  { company: "LaunchDarkly", token: "launchdarkly" },
  { company: "Lattice", token: "lattice" },
  { company: "Calendly", token: "calendly" },
  { company: "Marqeta", token: "marqeta" },
  { company: "Bill.com", token: "billcom" },
  { company: "Lithic", token: "lithic" },
  { company: "Fireblocks", token: "fireblocks" },
  { company: "Abnormal Security", token: "abnormalsecurity" },
  { company: "Tailscale", token: "tailscale" },
  { company: "Orca Security", token: "orcasecurity" },
  { company: "Dremio", token: "dremio" },
  { company: "Zipline", token: "flyzipline" },
  { company: "Figure", token: "figureai" },
  { company: "Aurora", token: "aurorainnovation" },
  { company: "Stability AI", token: "stabilityai" },
  { company: "Hume AI", token: "humeai" },
  { company: "AssemblyAI", token: "assemblyai" },
  { company: "Imbue", token: "imbue" },
  // More verified additions:
  { company: "xAI", token: "xai" },
  { company: "Waymo", token: "waymo" },
  { company: "Neuralink", token: "neuralink" },
  { company: "CoreWeave", token: "coreweave" },
  { company: "Ripple", token: "ripple" },
  { company: "Riot Games", token: "riotgames" },
  { company: "Epic Games", token: "epicgames" },
  { company: "Box", token: "boxinc" },
  { company: "Postman", token: "postman" },
  { company: "Qualtrics", token: "qualtrics" },
  { company: "Samsung Semiconductor", token: "samsungsemiconductor" },
  { company: "SambaNova", token: "sambanovasystems" },
  { company: "Lucid Motors", token: "lucidmotors" },
  { company: "Wayve", token: "wayve" },
  { company: "Astranis", token: "astranis" },
  { company: "Nubank", token: "nubank" },
  { company: "Recursion", token: "recursionpharmaceuticals" },
  // Quant / trading desks:
  { company: "Point72", token: "point72" },
  { company: "DRW", token: "drweng" },
  { company: "Schonfeld", token: "schonfeld" },
  { company: "Virtu Financial", token: "virtu" },
  { company: "Five Rings", token: "fiveringsllc" },
  { company: "Geneva Trading", token: "genevatrading" },
  { company: "DV Trading", token: "dvtrading" },
  // Fintech / SaaS / other:
  { company: "Adyen", token: "adyen" },
  { company: "Smartsheet", token: "smartsheet" },
  { company: "Carta", token: "carta" },
  { company: "Justworks", token: "justworks" },
  { company: "Highnote", token: "highnote" },
  { company: "Life360", token: "life360" },
  { company: "Komodo Health", token: "komodohealth" },
  { company: "Flatiron Health", token: "flatironhealth" },
  { company: "Vannevar Labs", token: "vannevarlabs" },
  { company: "Rocket Lab", token: "rocketlab" },
  { company: "Man Group", token: "mangroup" },
  { company: "Marshall Wace", token: "marshallwace" },
  { company: "Vatic Labs", token: "vaticlabs" },
  { company: "ZoomInfo", token: "zoominfo" },
  { company: "Betterment", token: "betterment" },
  { company: "Mercury", token: "mercury" },
  { company: "Amplitude", token: "amplitude" },
  { company: "Mixpanel", token: "mixpanel" },
  { company: "Intercom", token: "intercom" },
  { company: "Klaviyo", token: "klaviyo" },
  { company: "Braze", token: "braze" },
  { company: "Iterable", token: "iterable" },
  { company: "Customer.io", token: "customerio" },
  { company: "PlanetScale", token: "planetscale" },
  { company: "Netlify", token: "netlify" },
  { company: "Chainguard", token: "chainguard" },
  { company: "Huntress", token: "huntress" },
  { company: "Tines", token: "tines" },
  { company: "Pilot", token: "pilothq" },
  { company: "Alloy", token: "alloy" },
  { company: "Descript", token: "descript" },
  { company: "Omada Health", token: "omadahealth" },
  { company: "Path Robotics", token: "pathrobotics" },
  { company: "Epirus", token: "epirus" },
  { company: "Tenstorrent", token: "tenstorrent" },
  { company: "Graphcore", token: "graphcore" },
  { company: "Arize AI", token: "arizeai" },
  { company: "Mozilla", token: "mozilla" },
  { company: "Coursera", token: "coursera" },
  { company: "Udemy", token: "udemy" },
  { company: "Wikimedia", token: "wikimedia" },
  { company: "StackBlitz", token: "stackblitz" },
  { company: "Rockstar Games", token: "rockstargames" },
  { company: "Scopely", token: "scopely" },
  { company: "AlphaSense", token: "alphasense" },
  { company: "New Relic", token: "newrelic" },
  { company: "Sumo Logic", token: "sumologic" },
  { company: "Neo4j", token: "neo4j" },
  { company: "Databento", token: "databento" },
  { company: "WorldQuant", token: "worldquant" },
  { company: "Formic", token: "formic" },
  { company: "Allen Control Systems", token: "allencontrolsystems" },
  { company: "Vercel", token: "vercel" },
  { company: "Fastly", token: "fastly" },
  { company: "JFrog", token: "jfrog" },
  { company: "CircleCI", token: "circleci" },
  { company: "SingleStore", token: "singlestore" },
  { company: "YugabyteDB", token: "yugabyte" },
  { company: "Imply", token: "imply" },
  { company: "Pendo", token: "pendo" },
  { company: "Gradle", token: "gradle" },
  { company: "Algolia", token: "algolia" },
  { company: "Contentful", token: "contentful" },
  { company: "Storyblok", token: "storyblok" },
  { company: "Descope", token: "descope" },
  { company: "Salesloft", token: "salesloft" },
  { company: "Culture Amp", token: "cultureamp" },
  { company: "Remote", token: "remotecom" },
  { company: "Wrike", token: "wrike" },
  { company: "Dashlane", token: "dashlane" },
  { company: "Bitwarden", token: "bitwarden" },
  { company: "Cribl", token: "cribl" },
  { company: "Oura", token: "oura" },
  { company: "Agility Robotics", token: "agilityrobotics" },
  { company: "Jamf", token: "jamf" },
  { company: "Endor Labs", token: "endorlabs" },
  { company: "BitGo", token: "bitgo" },
  { company: "Consensys", token: "consensys" },
  { company: "Blockchain.com", token: "blockchain" },
  { company: "Instabase", token: "instabase" },
  { company: "Typeface", token: "typeface" },
  { company: "Mesh", token: "mesh" },
  { company: "Aptos Labs", token: "aptoslabs" },
  // Biotech / genomics:
  { company: "Natera", token: "natera" },
  { company: "10x Genomics", token: "10xgenomics" },
  { company: "Ginkgo Bioworks", token: "ginkgobioworks" },
  { company: "Arc Institute", token: "arcinstitute" },
  { company: "Generate Biomedicines", token: "generatebiomedicines" },
  // From speedyapply/2027-SWE-College-Jobs (probed live 2026-07-11):
  { company: "Apptronik", token: "apptronik" },
  { company: "Aquatic Capital Management", token: "aquaticcapitalmanagement" },
  { company: "BillionToOne", token: "billiontoone" },
  { company: "Lila Sciences", token: "lilasciences" },
  { company: "Podium", token: "podium81" },
  { company: "SpaceX", token: "spacex" },
  { company: "Varda", token: "vardaspace" },
  { company: "We. Communications", token: "wecommunications" },
  { company: "iHerb", token: "iherb" },
  { company: "Formlabs", token: "formlabs" },
  { company: "Clerkie", token: "clerkie" },
  { company: "Stoke Space", token: "stokespacetechnologies" },
  { company: "ASM", token: "asm" },
  // Probed live 2026-07-11 (candidate sweep, board name confirmed):
  { company: "AQR", token: "aqr" },
  { company: "Astera Labs", token: "asteralabs" },
  { company: "Hex", token: "hextechnologies" },
  { company: "Lightmatter", token: "lightmatter" },
  { company: "PsiQuantum", token: "psiquantum" },
  { company: "Roku", token: "roku" },
  { company: "Vast", token: "vast" },
  { company: "Wiz", token: "wizinc" },
  { company: "Zscaler", token: "zscaler" },
  { company: "Cohere Health", token: "coherehealth" },
  { company: "Da Vinci", token: "davinciderivatives" },
  { company: "Eikon Therapeutics", token: "eikontherapeutics" },
  { company: "Glean", token: "gleanwork" },
  { company: "Isomorphic Labs", token: "isomorphiclabs" },
  { company: "Maven Clinic", token: "mavenclinic" },
  { company: "Muon Space", token: "muonspace" },
  { company: "Qube Research & Technologies", token: "quberesearchandtechnologies" },
  { company: "Suki", token: "suki" },
  { company: "Together AI", token: "togetherai" },
  { company: "Ursa Major", token: "ursamajor" },
  { company: "Xaira Therapeutics", token: "xairatherapeutics" },
  // Probed live 2026-07-14 (candidate sweep, board name confirmed):
  { company: "Chaos Industries", token: "chaosindustries" },
  { company: "Cresta", token: "cresta" },
  { company: "FourKites", token: "fourkites" },
  { company: "Honeycomb", token: "honeycomb" },
  { company: "Kairos Power", token: "kairospower" },
  { company: "MatX", token: "matx" },
  { company: "Melio", token: "melio" },
  { company: "Mill", token: "mill" },
  { company: "Motive", token: "motive" },
  { company: "Navan", token: "tripactions" },
  { company: "Observe.AI", token: "observeai" },
  { company: "Oklo", token: "oklo" },
  { company: "Ondo Finance", token: "ondofinance" },
  { company: "Redwood Materials", token: "redwoodmaterials" },
  { company: "Regent", token: "regent" },
  { company: "Sila", token: "silananotechnologies" },
  { company: "project44", token: "project44" },
  // Probed live 2026-07-14 (candidate sweep, batch 2):
  { company: "Diligent Robotics", token: "diligentrobotics" },
  { company: "Nimble Robotics", token: "nimblerobotics" },
  { company: "World Labs", token: "worldlabs" },
  // Quant / trading — correct tokens (earlier sweep mis-guessed these), 2026-07-21:
  { company: "Chicago Trading Company", token: "chicagotrading" },
  { company: "ExodusPoint", token: "exoduspoint" },
  { company: "Jump Crypto", token: "jumpcrypto" },
  { company: "Quadrature", token: "quadraturecapital" },
  { company: "TransMarket Group", token: "transmarketgroup" },
  // AI lab (probed 2026-07-21):
  { company: "Thinking Machines", token: "thinkingmachines" },
  // Mined from aggregator apply-URLs — batch 1 (2026-07-22)
  { company: "10a Labs", token: "10alabs" },
  { company: "10Beauty", token: "10beauty" },
  { company: "1-800 Contacts", token: "1800contacts" },
  { company: "Abacus Insights", token: "abacusinsights" },
  { company: "AbelsonTaylor", token: "abelsontaylor" },
  { company: "AccuWeather", token: "accuweather" },
  { company: "ACLU Kentucky", token: "acluinternships" },
  { company: "Ada", token: "ada18" },
  { company: "Ad Council", token: "adcouncil" },
  { company: "Advanced Space", token: "advancedspace" },
  { company: "Aevex Aerospace", token: "aevexaerospace" },
  { company: "AgWest Farm Credit", token: "agwestfarmcredit" },
  { company: "AirCapture", token: "aircapture" },
  { company: "Alamar Biosciences", token: "alamarbiosciences" },
  { company: "Alarm.com", token: "alarmcom" },
  { company: "ALKU", token: "alku" },
  { company: "Alo Yoga", token: "aloyoga" },
  { company: "AMAROK Security", token: "amarok" },
  { company: "Amp Robotics", token: "ampsortation" },
  { company: "Antora Energy", token: "antora" },
  { company: "Apera AI", token: "aperaaiinc" },
  { company: "Apex Companies", token: "apexcompanies" },
  { company: "Appian", token: "appian" },
  { company: "Arcesium", token: "arcesiumllc" },
  { company: "Archer", token: "archer56" },
  { company: "Argmax", token: "argmax" },
  { company: "Armada", token: "armada" },
  { company: "Arvinas", token: "arvinas" },
  { company: "Astera Labs", token: "asteraearlycareer2026" },
  { company: "A Thinking Ape", token: "athinkingape" },
  { company: "Atlas Energy Solutions", token: "atlassand" },
  { company: "ATLAS SP", token: "atlassp" },
  { company: "Attain Partners", token: "attainpartners" },
  { company: "Attentive", token: "attentive" },
  { company: "Auctane", token: "auctane" },
  { company: "Audax Group", token: "audaxgroup" },
  { company: "Authentic", token: "authenticbrandsgroup" },
  { company: "AvePoint", token: "avepoint" },
  { company: "Avride", token: "avride" },
  { company: "Awetomaton", token: "awetomaton" },
  { company: "Axios", token: "axios" },
  { company: "Axon", token: "axon" },
  { company: "Axon", token: "axontalentcommunity" },
  { company: "AXQ Capital", token: "axq" },
  { company: "AXS", token: "axs" },
  { company: "Axsome Therapeutics Inc", token: "axsometherapeutics" },
  { company: "Aypa Power", token: "aypapower" },
  { company: "Babel Street", token: "babelstreet" },
  { company: "Major League Baseball", token: "baltimoreorioles" },
  { company: "BambooHR", token: "bamboohr17" },
  { company: "Bandwidth", token: "bandwidth" },
  { company: "Baselayer", token: "baselayer" },
  { company: "BetterHelp", token: "betterhelpcom" },
  { company: "BioMed Realty", token: "biomedrealty" },
  { company: "BlackEdge Capital", token: "blackedgecapital" },
  { company: "BlackSky", token: "blacksky" },
  { company: "BlueLabs Analytics", token: "bluelabsanalyticsinc" },
  { company: "Blue Sky Innovators", token: "blueskyinnovators" },
  { company: "Bluestaq", token: "bluestaq" },
  { company: "Bot Auto", token: "botauto" },
  { company: "Bracebridge Capital", token: "bracebridgecapital" },
  { company: "Breeze Airways", token: "breezeairways" },
  { company: "Brevium", token: "brevium" },
  { company: "BrightAI", token: "brightai" },
  { company: "Bugcrowd", token: "bugcrowd" },
  { company: "Calyxo", token: "calyxo" },
  { company: "Capital Technology Group", token: "capitaltg" },
  { company: "Carbon Direct", token: "carbondirect" },
  { company: "Cartesian", token: "cartesiansystems" },
  { company: "Climate Corps", token: "cc" },
  { company: "Cell Signaling Technology", token: "cellsignalingtechnology79" },
  { company: "Celonis", token: "celonis" },
  { company: "Clarity Innovations", token: "clarityinnovates" },
  { company: "CLEAR", token: "clear" },
  { company: "Clearway Energy", token: "clearwayjobs" },
  { company: "Clockwork Systems", token: "clockworksystems" },
  { company: "Cambridge Mobile Telematics", token: "cmt" },
  { company: "Cobalt", token: "cobaltio" },
  { company: "Codal", token: "codalinc" },
  { company: "Cognitiv", token: "cognitiv" },
  // aggregator-mined direct boards, batch 2 (2026-07-22)
  { company: "CoLab Software", token: "colabsoftware" },
  { company: "Commvault", token: "commvault" },
  { company: "Comstock Companies", token: "comstock" },
  { company: "Conner Strong & Buckelew", token: "connerstrongbuckelew" },
  { company: "Constant Contact", token: "constantcontact" },
  { company: "Construction Resources", token: "constructionresources" },
  { company: "Corcept Therapeutics", token: "corcepttherapeutics" },
  { company: "Correlation One", token: "correlationone" },
  { company: "Cortland", token: "cortland" },
  { company: "Critical Mass", token: "criticalmass" },
  { company: "CloudKitchens", token: "css" },
  { company: "Chicago Trading Company", token: "ctccampusboard" },
  { company: "Custom Computer Specialists", token: "customcomputerspecialists" },
  { company: "Dark Wolf Solutions", token: "darkwolfsolutions" },
  { company: "Defense Unicorns", token: "defenseunicorns" },
  { company: "Detroit Lions", token: "detroitlions" },
  { company: "DevRev", token: "devrev" },
  { company: "DH Pace", token: "dhpace" },
  { company: "Dialpad", token: "dialpad" },
  { company: "DiDi Global", token: "didi" },
  { company: "Digs", token: "digs" },
  { company: "Diligent Corporation", token: "diligentcorporation" },
  { company: "Docugami", token: "docugami" },
  { company: "Dorsia", token: "dorsia" },
  { company: "Double Good", token: "doublegood" },
  { company: "DoubleVerify", token: "doubleverify" },
  { company: "Doximity", token: "doximity" },
  { company: "DriveWealth", token: "drivewealth" },
  { company: "DRW", token: "drwuniversityjobs" },
  { company: "EarnIn", token: "earnin" },
  { company: "Echodyne", token: "echodynecorp" },
  { company: "edmentum", token: "edmentum" },
  { company: "Efficient Computer", token: "efficientcomputer" },
  { company: "Element Biosciences", token: "elementbiosciences" },
  { company: "Elevations Credit Union", token: "elevationscreditunion" },
  { company: "Maven Securities", token: "emergingtalent" },
  { company: "EnergyHub", token: "energyhub" },
  { company: "Eulerity", token: "eulerity" },
  { company: "Everlaw", token: "everlaw" },
  { company: "Evolver", token: "evolver" },
  { company: "Excel Sports Management", token: "excelsportsmanagement" },
  { company: "Correlation One", token: "expertnetwork" },
  { company: "ezCater", token: "ezcaterinc" },
  { company: "Fairlife", token: "fairlife" },
  { company: "Fussball Club Cincinnati LLC (\u201cFC Cincinnati\u201d)", token: "fccincinnati" },
  { company: "Figure", token: "figure" },
  { company: "Financial Technology Partners", token: "financialtechnologypartners" },
  { company: "Fireworks AI", token: "fireworksai" },
  { company: "Flagship Pioneering", token: "flagshippioneeringinc" },
  { company: "Focus Financial Partners", token: "focusfinancialpartners" },
  { company: "Foley Hoag", token: "foleyhoag" },
  { company: "Fortera", token: "forteracorporation" },
  { company: "Forward Networks", token: "forwardnetworks" },
  { company: "Found Energy", token: "foundenergy" },
  { company: "Four Hands", token: "fourhands" },
  { company: "Freeform", token: "freeformfuturecorp" },
  { company: "Health-E Commerce", token: "fsastorecom" },
  { company: "F. Schumacher & Co.", token: "fschumacherco" },
  { company: "Flagship Pioneering", token: "fspco-op012325" },
  { company: "Galaxy", token: "galaxydigitalservices" },
  { company: "Gametime", token: "gametimeunited" },
  { company: "Garda Capital Partners", token: "gardacp" },
  { company: "Gas South", token: "gassouth" },
  { company: "GCM Grosvenor", token: "gcmgrosvenor" },
  { company: "Gelber Group", token: "gelbergroup" },
  { company: "General Atlantic", token: "generalatlantic" },
  { company: "GenScript", token: "genscript" },
  { company: "Geotab", token: "geotab" },
  { company: "Notability", token: "gingerlabsinc" },
  { company: "Globalization Partners", token: "globalizationpartners" },
  { company: "GlossGenius", token: "glossgenius" },
  { company: "Glydways", token: "glydways" },
  { company: "GoFundMe", token: "gofundme" },
  { company: "Grassroots Analytics", token: "grassrootsanalytics" },
  { company: "Greenworks", token: "greenworkssunriseglobalmarketing" },
  { company: "GRVTY", token: "grvty" },
  { company: "Guidepoint", token: "guidepoint" },
  { company: "Haize Labs", token: "haizelabs" },
  { company: "Harbinger Motors", token: "harbingermotors" },
  { company: "Haven Studios", token: "haven" },
  // aggregator-mined direct boards, batch 3 (2026-07-22)
  { company: "HeartFlow", token: "heartflowinc" },
  { company: "HELLBENDER", token: "hellbenderinc" },
  { company: "HeyGen", token: "heygen" },
  { company: "Hive Financial Systems", token: "hivefinancialsystems" },
  { company: "Hone Health", token: "honehealth" },
  { company: "Horace Mann", token: "horacemannservicecorporation" },
  { company: "Horizon Industries", token: "horizonindustrieslimited" },
  { company: "Hudl", token: "hudl" },
  { company: "HumanSignal", token: "humansignal" },
  { company: "HPR (Hyannis Port Research)", token: "hyannisportresearch" },
  { company: "ID.me", token: "idmeuniversityrecruiting" },
  { company: "Impinj", token: "impinjexternal" },
  { company: "Impiricus", token: "impiricus" },
  { company: "IEM", token: "industrialelectricmanufacturing" },
  { company: "Inizio", token: "inizio" },
  { company: "Innodata", token: "innodatainc" },
  { company: "Inspire Medical Systems", token: "inspiremedicalsystemsinc" },
  { company: "Instawork", token: "instawork" },
  { company: "Instead", token: "instead" },
  { company: "Integra FEC", token: "integra" },
  { company: "Integra FEC", token: "integrainterns" },
  { company: "Geotab", token: "internshiplist2000" },
  { company: "Intrinsic", token: "intrinsicrobotics" },
  { company: "Iovance Biotherapeutics", token: "iovancebiotherapeutics" },
  { company: "iSpot.tv", token: "ispottv" },
  { company: "Ivalua", token: "ivalua" },
  { company: "IVX Health", token: "ivxhealth" },
  { company: "Jencap", token: "jencapinc" },
  { company: "Phamily", token: "jobsatphamily" },
  { company: "McKinney", token: "jobsmckinneycom" },
  { company: "Jumio", token: "jumio" },
  { company: "Juvare", token: "juvare" },
  { company: "Kapitus", token: "kapitus" },
  { company: "Kargo", token: "kargo" },
  { company: "Kensington", token: "kensingtontours" },
  { company: "Kikoff", token: "kikoff" },
  { company: "KnowBe4", token: "knowbe4" },
  { company: "Koddi", token: "koddi" },
  { company: "Kodiak Robotics", token: "kodiak" },
  { company: "Kroll Bond Rating Agency", token: "krollbondratingagency" },
  { company: "Labelbox", token: "labelbox" },
  { company: "Landscape Forms", token: "landscapeforms" },
  { company: "Lasko Products", token: "laskoproducts" },
  { company: "Later", token: "later" },
  { company: "Layer Health", token: "layerhealth" },
  { company: "League", token: "leagueinc" },
  { company: "Legend Biotech", token: "legendcareers" },
  { company: "LG Electronics", token: "lgelectronics" },
  { company: "Lightspeed Systems", token: "lightspeedsystems" },
  { company: "Locus Robotics", token: "locusrobotics" },
  { company: "LogicGate", token: "logicgate" },
  { company: "Lucid Bots", token: "lucidbots" },
  { company: "Lumos", token: "lumosfiber" },
  { company: "Lunar Energy", token: "lunarenergy" },
  { company: "Madison Energy Infrastructure", token: "madisonenergyinfrastructure" },
  { company: "Maybell Quantum Industries", token: "maybellquantum" },
  { company: "MCG Health", token: "mcghealth" },
  { company: "McMaster-Carr", token: "mcmastercarr" },
  { company: "MedElite", token: "medelitellc" },
  { company: "Medical Informatics Engineering", token: "medicalinformaticsengineering" },
  { company: "MEMIC", token: "memic" },
  { company: "MERGE", token: "mergeworld" },
  { company: "Meriton", token: "meriton" },
  { company: "MerQube", token: "merqube" },
  { company: "Method", token: "method" },
  { company: "MetOx International", token: "metoxinternationalinc" },
  { company: "Metron", token: "metron" },
  { company: "Minitab", token: "minitab" },
  { company: "Mobilityware", token: "mobilityware" },
  { company: "Moloco", token: "moloco" },
  { company: "Moment Energy", token: "momentenergy" },
  { company: "Marqeta", token: "mqreferrals" },
  { company: "Doctors Without Borders", token: "msfcareers" },
  { company: "mthree", token: "mthreerecruitingportal" },
  { company: "Marshall Wace", token: "mwinternshipprogram" },
  { company: "NPR", token: "nationalpublicradioinc" },
  { company: "NewsBreak", token: "newsbreak" },
  { company: "Newsela", token: "newsela" },
  { company: "Newton Research", token: "newtonresearch" },
  { company: "Nex", token: "nex" },
  // aggregator-mined direct boards, batch 4 (2026-07-22)
  { company: "The National Football League", token: "nflcareers" },
  { company: "Nimble Gravity", token: "nimblegravity" },
  { company: "National Information Solutions Cooperative (NISC)", token: "nisc" },
  { company: "Nooks", token: "nooks" },
  { company: "Northspyre", token: "northspyre" },
  { company: "NT Concepts", token: "ntconcepts" },
  { company: "Numerix", token: "numerix" },
  { company: "Obsidian Security", token: "obsidiansecurity" },
  { company: "OceanX", token: "oceanx" },
  { company: "Octaura", token: "octaura" },
  { company: "OfferUp", token: "offerup" },
  { company: "OBE", token: "oldcastlebuildingenvelope" },
  { company: "Olsson", token: "olsson" },
  { company: "Onapsis", token: "onapsis" },
  { company: "Open Farm Pet", token: "openfarminc" },
  { company: "OpenTable", token: "opentable" },
  { company: "Optiver", token: "optiverprivate" },
  { company: "Orennia", token: "orennia" },
  { company: "OTR Solutions", token: "otrcapital1" },
  { company: "Pacvue", token: "pacvue" },
  { company: "Pagaya Investments", token: "pagaya" },
  { company: "Palmetto Clean Technology", token: "palmettocleantech" },
  { company: "Parachute Health", token: "parachutehealth" },
  { company: "Parallel Systems", token: "parallel" },
  { company: "PatientPoint", token: "patientpoint" },
  { company: "Pendar Technologies", token: "pendartechnologies" },
  { company: "Perpay", token: "perpay" },
  { company: "Per Scholas", token: "perscholashires" },
  { company: "Phaidra", token: "phaidra" },
  { company: "Major League Baseball", token: "philliesbaseballoperations" },
  { company: "Phoenix Contact", token: "phoenixcontact" },
  { company: "Piaggio Fast Forward", token: "piaggiofastforward" },
  { company: "Planet", token: "planetlabs" },
  { company: "PLS", token: "plscareers" },
  { company: "PMG", token: "pmg" },
  { company: "Point C", token: "pointc" },
  { company: "Practising Law Institute", token: "practisinglawinstitute" },
  { company: "Praxent", token: "praxent" },
  { company: "Premier Automation", token: "premierautomation" },
  { company: "Presence", token: "presencelearning" },
  { company: "Profluent", token: "profluent" },
  { company: "Prolaio", token: "prolaio" },
  { company: "Pure Storage", token: "purestorage" },
  { company: "QGenda", token: "qgenda" },
  { company: "QuEra Computing", token: "queracomputinginc" },
  { company: "RA Capital Management", token: "racapitalmanagementllc" },
  { company: "Rackner", token: "rackner" },
  { company: "Radix Trading", token: "radixuniversity" },
  { company: "Realtor.com", token: "rdccareers" },
  { company: "Relay", token: "relaypro" },
  { company: "Rexford Industrial", token: "rexfordindustrial" },
  { company: "RF-SMART", token: "rfsmart" },
  { company: "Rhombus Power", token: "rhombuspower" },
  { company: "Rise8", token: "rise8" },
  { company: "RoboForce", token: "roboforce" },
  { company: "Rocket Lawyer", token: "rocketlawyer" },
  { company: "RTW Investments", token: "rtwinvestments" },
  { company: "Rugged Robotics", token: "ruggedrobotics" },
  { company: "Salient Motion", token: "salientmotion" },
  { company: "SALT XC", token: "saltxc" },
  { company: "Samaya", token: "samayaai" },
  { company: "Samsung Research America", token: "samsungresearchamericainternship" },
  { company: "SanMar", token: "sanmar" },
  { company: "Scout Motors", token: "scoutmotors" },
  { company: "Scout Space", token: "scoutspace" },
  { company: "Seurat Technologies", token: "seurat" },
  { company: "Seven Research", token: "sevenresearch" },
  { company: "Sezzle", token: "sezzle" },
  { company: "SharkNinja", token: "sharkninjaoperatingllc" },
  { company: "SHEIN", token: "shein" },
  { company: "Signifyd", token: "signifyd95" },
  { company: "Simple Technology Solutions", token: "simpletechnologysolutions" },
  { company: "Sixth Street", token: "sixthstreet" },
  { company: "SK hynix", token: "skhynixamerica" },
  { company: "SK Hynix Memory Solution", token: "skhynixmemorysolutionsamericainc" },
  { company: "Skyryse", token: "skyryse" },
  { company: "Smartly.io", token: "smartlyio" },
  { company: "Snorkel AI", token: "snorkelai" },
  { company: "Solid Power", token: "solidpower" },
  { company: "Sonatus", token: "sonatus" },
  // aggregator-mined direct boards, batch 5 (2026-07-22)
  { company: "Sono Bello", token: "sonobello" },
  { company: "SonoThera", token: "sonothera" },
  { company: "Sony Interactive Entertainment", token: "sonyinteractiveentertainmentglobal" },
  { company: "Space Kinetic", token: "spacekinetic" },
  { company: "Sparksoft", token: "sparksoftcorporation" },
  { company: "SpecterOps", token: "specterops" },
  { company: "SpyCloud", token: "spycloud" },
  { company: "Starburst", token: "starburst" },
  { company: "Strand Therapeutics", token: "strandtherapeutics" },
  { company: "Strata Decision Technology", token: "stratacareers" },
  { company: "Striim", token: "striiminc" },
  { company: "KRAFTON", token: "studiokraftonboard" },
  { company: "SupplyHouse.com", token: "supplyhouse" },
  { company: "STR", token: "systemstechnologyresearch" },
  { company: "Take Two", token: "taketwo" },
  { company: "Tastylive", token: "tastylive" },
  { company: "tastytrade", token: "tastytrade" },
  { company: "Tatari", token: "tatari" },
  { company: "Technergetics", token: "technergetics" },
  { company: "Tecovas", token: "tecovas" },
  { company: "Tenon", token: "tenon" },
  { company: "Tenstorrent", token: "tenstorrentuniversity" },
  { company: "Terran Orbital", token: "terranorbitalcorporation" },
  { company: "National Information Solutions Cooperative (NISC)", token: "testnisc" },
  { company: "The Allen Institute for AI", token: "thealleninstitute" },
  { company: "The Health Management Academy", token: "thehealthmanagementacademy" },
  { company: "The New York Times", token: "thenewyorktimes" },
  { company: "The Scion Group", token: "thesciongroupllc" },
  { company: "The Trade Desk", token: "thetradedesk" },
  { company: "The Weather Company", token: "theweathercompany" },
  { company: "Torc Robotics", token: "torcrobotics" },
  { company: "Toshiba Global Commerce", token: "toshibaglobalcommercesolutions" },
  { company: "Trexon", token: "tpcengineeringholdingsllc" },
  { company: "Optiver", token: "tradingacademy2025" },
  { company: "TribalScale", token: "tribalscale" },
  { company: "TripAdvisor", token: "tripadvisor" },
  { company: "TripArc", token: "triparc" },
  { company: "True Anomaly", token: "trueanomalyinc" },
  { company: "Trumid", token: "trumid" },
  { company: "Truveta", token: "truveta" },
  { company: "Tubi", token: "tubitv" },
  { company: "Two Six Technologies", token: "twosixtechnologies" },
  { company: "Uber Freight", token: "uberfreight" },
  { company: "Udemy", token: "udemybedi" },
  { company: "Ultima Genomics", token: "ultimagenomics" },
  { company: "UnitedMasters", token: "unitedmasterstranslation" },
  { company: "Upstream USA", token: "upstreamusa" },
  { company: "US Conec", token: "usconec" },
  { company: "Vera Institute of Justice", token: "verainstituteofjustice" },
  { company: "Verisign", token: "verisign" },
  { company: "Vestwell", token: "vestwell" },
  { company: "Viking Global", token: "vikingglobalinvestors" },
  { company: "Virtru", token: "virtru" },
  { company: "Virtu Financial", token: "virturecruitinghidden" },
  { company: "Vise", token: "viseai" },
  { company: "Visier Solutions", token: "visiersolutionsinc" },
  { company: "Vixxo", token: "vixxo" },
  { company: "Voloridge", token: "voloridgeinvestmentmanagement" },
  { company: "Voyager Technologies", token: "voyagertechnologiesinc" },
  { company: "VSC Fire & Security", token: "vscfiresecurityinc" },
  { company: "Vulcan Elements", token: "vulcanelements" },
  { company: "Walleye Capital", token: "walleyecapital-external-students" },
  { company: "Wasabi Technologies", token: "wasabi" },
  { company: "Weiss Asset Management", token: "weissassetmanagement" },
  { company: "Wheely", token: "wheely" },
  { company: "WhiteWater Midstream", token: "whitewatermidstream" },
  { company: "Workato", token: "workato" },
  { company: "Workstream", token: "workstream" },
  { company: "World Surf League", token: "worldsurfleague" },
  { company: "WPP Media", token: "wppmedia" },
  { company: "Wurl", token: "wurljobs" },
  { company: "Xebia", token: "xebiausa" },
  { company: "Xometry", token: "xometry" },
  { company: "XPENG Motors", token: "xpengmotors" },
  { company: "Yes Energy", token: "yesenergy" },
  { company: "YOU.com", token: "youcom" },
  { company: "Zocdoc", token: "zocdoc" },
  { company: "Zone 5 Technologies", token: "zone5technologies" },
];

interface GhJob {
  title?: unknown;
  absolute_url?: unknown;
  updated_at?: unknown;
  location?: { name?: unknown };
}

async function fetchCompany(c: AtsCompany): Promise<AtsJob[]> {
  const raw = await fetchJson(
    `https://boards-api.greenhouse.io/v1/boards/${c.token}/jobs?content=false`,
  );
  const jobs = (raw as { jobs?: GhJob[] })?.jobs ?? [];
  return jobs.map((j) => ({
    title: typeof j.title === "string" ? j.title.trim() : "",
    locations: typeof j.location?.name === "string" ? [j.location.name.trim()] : [],
    url: typeof j.absolute_url === "string" ? j.absolute_url : "",
    // Greenhouse's list endpoint exposes updated_at, not a true posted date — a
    // close-enough freshness proxy (new roles have a recent timestamp).
    datePosted: parseIsoDate(j.updated_at),
  }));
}

export const greenhouseSource: Source = {
  name: SOURCE_NAME,
  load: () => loadAts({ sourceName: SOURCE_NAME, companies: BOARDS, fetchCompany }),
};
