import { fetchJson } from "@/lib/ingest/http";
import { loadAts, type AtsCompany, type AtsJob } from "@/lib/ingest/sources/ats";
import type { Source } from "@/lib/ingest/types";

const SOURCE_NAME = "lever";

// Display name -> Lever org slug (api.lever.co/v0/postings/{slug}).
const BOARDS: AtsCompany[] = [
  { company: "Palantir", token: "palantir" },
  { company: "Ro", token: "ro" },
  { company: "Veeva", token: "veeva" },
  { company: "GoPuff", token: "gopuff" },
  { company: "Spotify", token: "spotify" },
  { company: "Mistral AI", token: "mistral" },
  // From speedyapply/2027-SWE-College-Jobs (probed live 2026-07-11):
  { company: "Fluxergy", token: "fluxergy-2" },
  { company: "GenBio AI", token: "genbio" },
  { company: "Hermeus", token: "hermeus" },
  { company: "Plus", token: "plus-2" },
  { company: "Rainmaker", token: "make-rain" },
  { company: "SoloPulse", token: "solopulseco" },
  { company: "Traackr", token: "traackr" },
  // Probed live 2026-07-11 (candidate sweep):
  { company: "Atom Computing", token: "atomcomputing" },
  { company: "Shield AI", token: "shieldai" },
  { company: "Waabi", token: "waabi" },
  { company: "Zoox", token: "zoox" },
  { company: "Belvedere Trading", token: "belvederetrading" },
  { company: "Dexterity", token: "dexterity" },
  { company: "Included Health", token: "includedhealth" },
  // Probed live 2026-07-14 (candidate sweep):
  { company: "Anchorage Digital", token: "anchorage" },
  { company: "Loadsmart", token: "loadsmart" },
  { company: "Merlin Labs", token: "merlinlabs" },
  // Probed live 2026-07-14 (candidate sweep, batch 2):
  { company: "Metabase", token: "metabase" },
  { company: "Pickle Robot", token: "picklerobot" },
  { company: "Sysdig", token: "sysdig" },
  // Robotics (probed 2026-07-21):
  { company: "Bright Machines", token: "brightmachines" },
  // aggregator-mined direct boards, batch 1 (2026-07-22)
  { company: "Acceldata", token: "acceldata" },
  { company: "Achievers", token: "achievers" },
  { company: "Actian", token: "actian" },
  { company: "Aledade", token: "aledade" },
  { company: "Alertus Technologies", token: "alertus" },
  { company: "Allegiant Air", token: "allegiantair" },
  { company: "AllTrails", token: "alltrails" },
  { company: "AltaML", token: "altaml" },
  { company: "Analytic Partners", token: "analyticpartners" },
  { company: "Anomali", token: "anomali" },
  { company: "Appen", token: "appen-2" },
  { company: "Aquabyte", token: "aquabyte" },
  { company: "ArteraAI", token: "artera" },
  { company: "BenchSci", token: "benchsci" },
  { company: "Behaviour Interactive", token: "bhvr" },
  { company: "BioAgilytix", token: "bioagilytix" },
  { company: "Brooks Running", token: "brooksrunning" },
  { company: "Cirque du Soleil", token: "cirquedusoleil" },
  { company: "CLO Virtual Fashion", token: "clovirtualfashion" },
  { company: "Coupa Software", token: "coupa" },
  { company: "Crest Industries", token: "crestoperations" },
  { company: "Daniels Health", token: "daniels-sharpsmart" },
  { company: "Democratic Governors Association", token: "dga" },
  { company: "Diversified Automation", token: "diversified-automation" },
  { company: "OraSure Technologies", token: "dnagenotek" },
  { company: "HRL Laboratories", token: "dodmg" },
  { company: "Drivemode", token: "drivemode" },
  { company: "Lightcast", token: "economicmodeling" },
  { company: "Ekimetrics", token: "ekimetrics" },
  { company: "Elf Beauty", token: "elfbeauty" },
  { company: "Endpoint Clinical", token: "endpointclinical" },
  { company: "EQ Bank", token: "eqbank" },
  { company: "Equativ", token: "equativ" },
  { company: "Empire State Realty Trust", token: "esrtreit" },
  { company: "EV Realty", token: "evrealty-us" },
  { company: "Exowatt", token: "exowatt" },
  { company: "Extreme Networks", token: "extremenetworks" },
  { company: "Farfetch", token: "farfetch" },
  { company: "Fehr & Peers", token: "fehrandpeers" },
  { company: "Field AI", token: "field-ai" },
  { company: "Firemon", token: "firemon" },
  { company: "Fullscript", token: "fullscript" },
  { company: "GeoComply", token: "geocomply-2" },
  { company: "Cloudforce", token: "go-cloudforce" },
  { company: "GoMaterials", token: "gomaterials" },
  { company: "Gr0", token: "gr0" },
  { company: "Great Gray", token: "great-gray-group" },
  { company: "Greenlight", token: "greenlight" },
  { company: "Hanna Andersson", token: "hannaandersson" },
  { company: "Ibility", token: "ibility" },
  { company: "Ideas United", token: "ideasunited" },
  { company: "Institute of Foundation Models", token: "ifm-us" },
  { company: "IMO Health", token: "imo-online" },
  { company: "Intropic", token: "intropic" },
  { company: "ION Group", token: "ion" },
  { company: "ispace", token: "ispace-inc" },
  { company: "Kabam", token: "kabam" },
  { company: "Kepler Communications", token: "kepler" },
  { company: "Kpler", token: "kpler" },
  { company: "Larian Studios", token: "larian" },
  { company: "Lendbuzz", token: "lendbuzz" },
  { company: "Level AI", token: "levelai" },
  { company: "Lexeo Therapeutics", token: "lexeotx" },
  { company: "Link", token: "linkllc" },
  // aggregator-mined direct boards, batch 2 (2026-07-22)
  { company: "Long Wall", token: "longwall" },
  { company: "LTA Research", token: "ltaresearch" },
  { company: "Lumafield", token: "lumafield" },
  { company: "Magnet Forensics", token: "magnetforensics" },
  { company: "Massachusetts School Building Authority", token: "massschoolbuildings" },
  { company: "Multiply Labs", token: "multiplylabs" },
  { company: "Neighbor", token: "neighbor" },
  { company: "Nextech Systems", token: "nextech" },
  { company: "NextGen Federal Systems", token: "nextgenfed" },
  { company: "Nobull", token: "nobullproject" },
  { company: "Octopus Energy", token: "octoenergy" },
  { company: "Oleria Security", token: "oleria-security" },
  { company: "OpenX", token: "openx" },
  { company: "Parallel Wireless", token: "parallelwireless" },
  { company: "Penumbra Inc", token: "penumbrainc" },
  { company: "PingWind", token: "pingwind" },
  { company: "Pivotal Software", token: "pivotal" },
  { company: "Pivot Energy", token: "pivotenergy" },
  { company: "Prosper Funding", token: "prosper" },
  { company: "Quandri", token: "quandri" },
  { company: "QuantCo", token: "quantco-" },
  { company: "Quest Analytics", token: "questanalytics" },
  { company: "RAVL", token: "ravl_io" },
  { company: "Redhorse", token: "redhorsecorp" },
  { company: "Redwood Credit Union", token: "redwoodcu" },
  { company: "Reply", token: "reply" },
  { company: "Rigetti", token: "rigetti" },
  { company: "Robust.ai", token: "robust-ai" },
  { company: "RWS", token: "rws" },
  { company: "Samba TV", token: "sambatv" },
  { company: "Secureframe", token: "secureframe" },
  { company: "SF Giants", token: "sfgiants" },
  { company: "SFMOMA", token: "sfmoma" },
  { company: "Reli", token: "shopreli" },
  { company: "ShyftLabs", token: "shyftlabs" },
  { company: "Skyways", token: "skyways" },
  { company: "Stand Together", token: "standtogether" },
  { company: "SteerBridge", token: "steerbridge" },
  { company: "SunSource", token: "sunsrce" },
  { company: "Sunwater Capital", token: "sunwatercapital" },
  { company: "Syntax", token: "syntax" },
  { company: "Synthego", token: "synthego" },
  { company: "Tahoe Therapeutics", token: "tahoebio-ai" },
  { company: "Tekton", token: "tekton" },
  { company: "Teleo", token: "teleo" },
  { company: "Telesat", token: "telesat" },
  { company: "Telligen", token: "telligen" },
  { company: "The Information Lab", token: "theinformationlab" },
  { company: "AHEAD", token: "thinkahead" },
  { company: "Thinkingbox", token: "thinkingbox" },
  { company: "Toyota Research Institute", token: "tri" },
  { company: "UntilLabs", token: "until" },
  { company: "Very Good Security", token: "verygoodsecurity" },
  { company: "Vevo", token: "vevo" },
  { company: "Vivenu", token: "vivenu" },
  { company: "Voltus", token: "voltus" },
  { company: "Wade Trim", token: "wadetrim" },
  { company: "WeRide", token: "weride" },
  { company: "Wintermute", token: "wintermute-trading" },
  { company: "Woven", token: "woven-by-toyota" },
  { company: "Xsolla", token: "xsolla" },
  { company: "zaimler", token: "zaimler" },
  { company: "Zus Health", token: "zushealth" },
  // Probed live 2026-08-04 (2027-cycle sweep). Lever slugs are case-sensitive.
  { company: "AI Fund", token: "AIFund" },
  { company: "CesiumAstro", token: "CesiumAstro" },
  { company: "Energy Vault", token: "EnergyVault" },
  { company: "Mercedes-Benz R&D North America", token: "MBRDNA" },
  { company: "Beta Technologies", token: "beta" },
  { company: "Sanctuary AI", token: "sanctuary" },
  { company: "Wealthfront", token: "wealthfront" },
  { company: "Best Egg", token: "BestEgg" },
  { company: "Symmetry Systems", token: "SymmetrySystems" },
  { company: "Sprinter Health", token: "SprinterHealth" },
  { company: "Center for AI Safety", token: "aisafety" },
  { company: "2nd Order Solutions", token: "2os" },
  { company: "BlueRock Therapeutics", token: "bluerocktx" },
  { company: "Ivo", token: "ivo" },
  { company: "Grid", token: "Grid" },
  { company: "Quantum Workplace", token: "QuantumWorkplace" },
  { company: "Aprio", token: "Aprio" },
  { company: "CALSTART", token: "calstart" },
  { company: "Age of Learning", token: "aofl" },
  { company: "ButcherBox", token: "butcherbox" },
  { company: "New Jersey Innovation Authority", token: "NJStateOfficeofInnovation" },
  { company: "Arc'teryx", token: "arcteryx.com" },

  // Mined 2026-08-05 from the aggregator feeds' apply-URLs (they embed the ATS
  // token verbatim), then each of these 129 boards probed once and kept only on
  // a 200 with at least one live posting. Screened three ways before landing:
  // one board per employer, no company already covered by another source (a
  // second display name for one employer splits it in two — company feeds
  // listingId), and the display name taken from the ATS's own board name where
  // it reports one, else from the feed.
  { company: "3PillarGlobal", token: "3pillarglobal" },
  { company: "Aera Technology", token: "aeratechnology" },
  { company: "Agate Software", token: "agatesoftware" },
  { company: "Agile Defense", token: "agile-defense" },
  { company: "Agtonomy", token: "agtonomy" },
  { company: "Aircall", token: "aircall" },
  { company: "Arable", token: "arable" },
  { company: "Arrive Logistics", token: "arrivelogistics" },
  { company: "Artera", token: "artera-2" },
  { company: "Autoroboto", token: "autoroboto" },
  { company: "Avia Health", token: "aviahealth" },
  { company: "Beghou Consulting", token: "beghouconsulting" },
  { company: "Bellese", token: "bellese" },
  { company: "Bellwether", token: "bellwetheram-2" },
  { company: "Bisnow", token: "bisnow" },
  { company: "Boson Ai", token: "bosonai" },
  { company: "Bumble", token: "bumbleinc" },
  { company: "Canvas Worldwide", token: "canvasww" },
  { company: "Catalist", token: "catalist" },
  { company: "Certik", token: "certik" },
  { company: "CGS Federal (Contact Government Services)", token: "cgsfederal" },
  { company: "City Electrical Factors", token: "cef" },
  { company: "Civitech", token: "civitech" },
  { company: "CleanSpark", token: "cleanspark" },
  { company: "Clearer.io", token: "Clearer" },
  { company: "Colibri Group", token: "colibrigroup" },
  { company: "CompassX Group", token: "compassx" },
  { company: "Conversica", token: "conversica" },
  { company: "CrowdGen by Appen", token: "appen" },
  { company: "Crumbl", token: "crumbl" },
  { company: "CX2", token: "cx2" },
  { company: "Datalab USA", token: "datalabusa" },
  { company: "Dun & Bradstreet", token: "dnb" },
  { company: "Dutch", token: "dutch" },
  { company: "Eastern Research Group", token: "erg" },
  { company: "Easy Street Capital", token: "easystreetcap" },
  { company: "Eliyan", token: "eliyan" },
  { company: "Employ", token: "employ" },
  { company: "Ethena", token: "ethena" },
  { company: "Filevine", token: "filevine" },
  { company: "FinQuery", token: "finquery" },
  { company: "FiscalNote", token: "fiscalnote" },
  { company: "FOTH", token: "foth" },
  { company: "Girls Who Code", token: "girlswhocode" },
  { company: "Global Lending Services", token: "glsllc" },
  { company: "GRAIL", token: "grailbio" },
  { company: "Gynger", token: "gynger" },
  { company: "H1", token: "h1" },
  { company: "Hatch IT", token: "hatchit" },
  { company: "hhaexchange", token: "hhaexchange" },
  { company: "Hive", token: "hive" },
  { company: "Istari Digital", token: "istaridigital.ai" },
  { company: "Jam City", token: "jamcity" },
  { company: "K Group", token: "kgroupcompanies" },
  { company: "Kitware", token: "kitware" },
  { company: "Latitude", token: "latitudeinc" },
  { company: "LCBC Church", token: "lcbcchurch" },
  { company: "Life.Church", token: "life" },
  { company: "Lightship RV", token: "lightship" },
  { company: "Lumotive", token: "lumotive" },
  { company: "Luxury Presence", token: "luxurypresence" },
  { company: "MARGO", token: "margo-group" },
  { company: "Mastery Charter Schools", token: "masterycharter" },
  { company: "Matillion", token: "matillion" },
  { company: "MCA Connect", token: "mcaconnect" },
  { company: "Meds", token: "meds" },
  { company: "Mendix", token: "mendix" },
  { company: "Metergy Solutions", token: "metergysolutions" },
  { company: "Model N", token: "modeln" },
  { company: "Monterey Technologies", token: "mti-inc" },
  { company: "moo", token: "moo" },
  { company: "Moonpig", token: "moonpig" },
  { company: "N-Power Medicine", token: "npowermedicine" },
  { company: "Nomi Health", token: "nomihealth" },
  { company: "OakNorth Bank", token: "oaknorth.ai" },
  { company: "Olo", token: "olo" },
  { company: "Omni Design Technologies", token: "omnidesigntech" },
  { company: "OptionMetrics", token: "optionmetrics" },
  { company: "Orb Aerospace", token: "orbaerospace" },
  { company: "Parkdepot", token: "salesdemo-jr" },
  { company: "Pigment", token: "pigment" },
  { company: "Planet Technologies", token: "planettechnologies" },
  { company: "Protective Life", token: "protective" },
  { company: "Protolabs", token: "protolabs" },
  { company: "Q-CTRL", token: "q-ctrl" },
  { company: "Revefi", token: "revefi" },
  { company: "Revenue Analytics", token: "revenueanalytics" },
  { company: "Salvo Health", token: "salvohealth" },
  { company: "Saviynt", token: "saviynt" },
  { company: "Schmidt Sciences", token: "schmidt-entities" },
  { company: "Scott Logic", token: "scottlogic" },
  { company: "Seer Interactive", token: "seerinteractive" },
  { company: "Simbe Robotics", token: "SimbeRobotics" },
  { company: "Simulmedia", token: "simulmedia" },
  { company: "Sonar", token: "sonarsource" },
  { company: "Sophos", token: "sophos" },
  { company: "Spry Methods", token: "sprymethods" },
  { company: "SpryPoint", token: "sprypointservices" },
  { company: "SQA Services", token: "sqaservices" },
  { company: "StarCompliance", token: "starcompliance" },
  { company: "Strada Education Foundation", token: "stradaeducation" },
  { company: "SugarCRM", token: "sugarcrm" },
  { company: "Synergy ECP", token: "synergyecp" },
  { company: "TalentWerx", token: "talentwerx.io" },
  { company: "Tangram Interiors", token: "tangraminteriors" },
  { company: "Tevora", token: "tevora" },
  { company: "The Trevor Project", token: "thetrevorproject" },
  { company: "Theodo", token: "theodo" },
  { company: "Thomas & Hutton", token: "tandh" },
  { company: "Tinder", token: "matchgroup" },
  { company: "Trackforce", token: "tracktik" },
  { company: "Trend Health Partners", token: "Trend-Health-Partners" },
  { company: "TreviPay", token: "trevipay" },
  { company: "Trio", token: "trio" },
  { company: "TrueTandem", token: "truetandem" },
  { company: "TSMG", token: "tsmg" },
  { company: "Unison Infrastructure", token: "unisoninfra" },
  { company: "Upscale AI", token: "upscale-ai" },
  { company: "Versapay", token: "versapay" },
  { company: "Wachter", token: "wachter" },
  { company: "WebFX", token: "webfx" },
  { company: "Welo Global", token: "weloglobal" },
  { company: "Windfall", token: "windfalldata" },
  { company: "Wing Assistant", token: "getwingapp" },
  { company: "World Wide Professional Solutions", token: "wwprosolutions" },
  { company: "Wpromote", token: "wpromote" },
  { company: "Wyetech", token: "wyetechllc" },
  { company: "Xpansiv", token: "Xpansiv " },
  { company: "Zopa", token: "zopa" },
];

interface LeverJob {
  text?: unknown;
  hostedUrl?: unknown;
  createdAt?: unknown;
  categories?: { location?: unknown; allLocations?: unknown; commitment?: unknown };
}

function locations(cats: LeverJob["categories"]): string[] {
  if (Array.isArray(cats?.allLocations)) {
    return cats!.allLocations.filter((x): x is string => typeof x === "string");
  }
  return typeof cats?.location === "string" ? [cats.location] : [];
}

async function fetchCompany(c: AtsCompany): Promise<AtsJob[]> {
  // Encoded, because a few Lever slugs contain a space ("Xpansiv "). Tokens are
  // stored decoded so the registry holds the slug itself and not one particular
  // escaping of it — encoding here is what makes that safe. No-op for the rest:
  // encodeURIComponent leaves alphanumerics and - . _ ~ alone.
  const raw = await fetchJson(
    `https://api.lever.co/v0/postings/${encodeURIComponent(c.token)}?mode=json`,
  );
  if (!Array.isArray(raw)) return [];
  return (raw as LeverJob[]).map((j) => ({
    title: typeof j.text === "string" ? j.text.trim() : "",
    locations: locations(j.categories),
    url: typeof j.hostedUrl === "string" ? j.hostedUrl : "",
    // Lever gives a real creation timestamp (epoch ms).
    datePosted:
      typeof j.createdAt === "number" && j.createdAt > 0
        ? new Date(j.createdAt)
        : null,
  }));
}

export const leverSource: Source = {
  name: SOURCE_NAME,
  load: () => loadAts({ sourceName: SOURCE_NAME, companies: BOARDS, fetchCompany }),
};
